window.quizQuestions = [
  {
    id: 1,
    lecture: "第一讲",
    topic: "网络构成",
    question: "按照课件对计算机网络构成的划分，连接端系统和网络核心、包含通信链路的是哪一部分？",
    options: ["接入网", "应用层", "控制平面", "传输层"],
    answer: 0,
    source: "第一讲_(2) 网络基础知识.pptx · 第 6-8 页",
    detail: "课件把计算机网络划分为网络边缘、接入网和网络核心。接入网负责把边缘端系统连接到网络核心，典型链路包括光纤、铜缆、无线电等。"
  },
  {
    id: 2,
    lecture: "第一讲",
    topic: "路由与转发",
    question: "下列哪一项最符合“路由”和“转发”的区别？",
    options: ["路由决定路径，转发按已有表项把分组送到下一跳", "路由只发生在主机上，转发只发生在应用层", "路由负责差错检测，转发负责加密", "二者含义完全相同"],
    answer: 0,
    source: "第一讲_(2) 网络基础知识.pptx · 第 37 页",
    detail: "路由是全局层面的路径规划，通常通过路由算法计算并形成路由表；转发是单个节点上的执行动作，根据表项把收到的数据送往合适的输出端口或下一跳。"
  },
  {
    id: 3,
    lecture: "第一讲",
    topic: "分组交换",
    question: "关于分组交换的说法，哪一项是正确的？",
    options: ["把大消息拆成分组，并以分组为单位传输", "通信前必须为整条路径永久预留带宽", "所有分组必须永远走同一条物理电路", "不会产生排队时延和丢包"],
    answer: 0,
    source: "第一讲_(2) 网络基础知识.pptx · 第 40 页",
    detail: "分组交换把消息拆成较小的 packet，每个分组携带首部并作为传输单元。它适合突发数据和共享链路，但也可能因为拥塞产生排队时延甚至丢包。"
  },
  {
    id: 4,
    lecture: "第一讲",
    topic: "存储转发",
    question: "“存储-转发”机制中，路由器什么时候才能开始向下一跳发送一个分组？",
    options: ["完整接收到整个分组之后", "接收到第一个比特之后立刻发送", "只要知道目的 IP 就能提前发送", "等整条端到端路径空闲之后"],
    answer: 0,
    source: "第一讲_(2) 网络基础知识.pptx · 第 41 页",
    detail: "课件强调存储转发要求路由器先完整接收整个数据包，然后才开始向下一跳发送。这会带来额外的传输延迟。"
  },
  {
    id: 5,
    lecture: "第一讲",
    topic: "性能指标",
    question: "下列哪一项最准确地区分了“带宽”和“吞吐量”？",
    options: ["带宽偏向信道最高能力，吞吐量偏向实际通过的数据量", "带宽只用于无线网络，吞吐量只用于有线网络", "带宽等于丢包率，吞吐量等于时延", "二者没有区别，都是 RTT"],
    answer: 0,
    source: "第一讲_(2) 网络基础知识.pptx · 第 70-72 页",
    detail: "带宽表示某信道单位时间能通过的最高数据率；吞吐量表示单位时间实际通过某个网络位置或信道的数据量。考试中常考“能力上限”和“实际表现”的区别。"
  },
  {
    id: 6,
    lecture: "第一讲",
    topic: "时延",
    question: "网络总时延通常写作 dtotal = dproc + dqueue + dtrans + dprop，其中最不确定、受拥塞影响最明显的是哪一项？",
    options: ["排队时延 dqueue", "传播时延 dprop", "处理时延 dproc", "传输时延 dtrans"],
    answer: 0,
    source: "第一讲_(2) 网络基础知识.pptx · 第 56-67 页",
    detail: "处理、传输、传播时延通常可以根据设备、包长、速率和距离估算；排队时延取决于流量到达和队列状态，是最不稳定的一项。"
  },
  {
    id: 7,
    lecture: "第一讲",
    topic: "协议",
    question: "在网络协议中，“消息有哪些字段、字段取值如何组织”主要属于哪一类内容？",
    options: ["语法", "物理介质", "吞吐量", "传播速度"],
    answer: 0,
    source: "第一讲_(2) 网络基础知识.pptx · 第 75 页；第二讲_应用层-(1)Web与HTTP.pptx · 第 28 页",
    detail: "协议规定通信双方如何交换消息。应用层协议通常包括消息类型、消息语法、消息语义和处理规则；字段组织和取值格式属于语法。"
  },
  {
    id: 8,
    lecture: "第二讲",
    topic: "TCP 与 UDP",
    question: "课件中对传输层服务的概括里，TCP 提供而 UDP 不提供的是哪一项？",
    options: ["面向连接、可靠传输、流量控制和拥塞控制", "完全无延迟传输", "无需端口号即可分用", "不需要任何传输层首部"],
    answer: 0,
    source: "第二讲_应用层-(1)Web与HTTP.pptx · 第 8 页；第三讲_传输层(1)基本概念、UDP.pptx · 第 19 页",
    detail: "TCP 服务包括面向连接、可靠和有序传输、流量控制、拥塞控制等；UDP 是对网络层接口的最简封装，保留端口分用和校验等基本功能。"
  },
  {
    id: 9,
    lecture: "第二讲",
    topic: "P2P",
    question: "与客户端-服务器架构相比，P2P 架构的典型特点是？",
    options: ["节点既可以请求服务，也可以提供服务", "所有节点必须始终在线且角色固定", "只能用于电子邮件", "必须由单个中心服务器保存全部数据"],
    answer: 0,
    source: "第二讲_应用层-(1)Web与HTTP.pptx · 第 26 页；第二讲_应用层-(3)其他应用层协议.pptx · 第 3-7 页",
    detail: "P2P 中每个 peer 往往既是客户端也是服务器，能够直接与其他 peer 交换资源。它扩展性好，但需要额外的索引、发现和管理机制。"
  },
  {
    id: 10,
    lecture: "第二讲",
    topic: "HTTP",
    question: "关于 HTTP/1.0 与 HTTP/1.1，哪一项符合课件内容？",
    options: ["HTTP/1.0 默认非持久连接，HTTP/1.1 支持长连接和流水线机制", "HTTP/1.1 删除了缓存机制", "HTTP/1.0 使用 QUIC 作为传输层", "HTTP/1.1 不能传输 Web 对象"],
    answer: 0,
    source: "第二讲_应用层-(1)Web与HTTP.pptx · 第 47-50 页",
    detail: "课件列出 HTTP/1.0 的无状态、非持久连接特征，以及 HTTP/1.1 对长连接、流水线、缓存、部分资源请求等方面的支持。"
  },
  {
    id: 11,
    lecture: "第二讲",
    topic: "HTTP 方法",
    question: "GET 和 POST 的常见区别，哪一项说法更准确？",
    options: ["GET 参数通常放在 URL 中，POST 参数通常放在实体主体中", "GET 只能用于下载图片，POST 只能用于 DNS", "GET 必须加密，POST 不能加密", "二者在报文格式上完全没有区别"],
    answer: 0,
    source: "第二讲_应用层-(1)Web与HTTP.pptx · 第 55-60 页",
    detail: "课件指出 POST 也可以请求 URL 资源，关键区别在参数位置：GET 参数在请求行 URL 中，POST 参数在实体主体中，因此 POST 的参数长度通常不受 URL 长度限制。"
  },
  {
    id: 12,
    lecture: "第二讲",
    topic: "Cookie",
    question: "HTTP 是无状态协议，服务器常用什么机制在多次请求之间保持用户状态？",
    options: ["Cookie", "CRC", "ARP", "CSMA/CD"],
    answer: 0,
    source: "第二讲_应用层-(1)Web与HTTP.pptx · 第 73-76 页",
    detail: "服务器可在 HTTP 响应首部使用 Set-Cookie，后续请求携带该 cookie，从而让服务器识别同一用户或会话。"
  },
  {
    id: 13,
    lecture: "第二讲",
    topic: "DNS",
    question: "DNS 采用分布式域名服务器体系的主要好处不包括哪一项？",
    options: ["让所有查询必须集中到一台根服务器完成", "避免单点故障", "处理海量查询流量", "按层次结构管理域名空间"],
    answer: 0,
    source: "第二讲_应用层-(2)DNS、电子邮件.pptx · 第 8-10 页",
    detail: "DNS 的逻辑结构是分布式数据库，物理上由多个域名服务器完成查询。集中到一台服务器会带来单点故障和流量瓶颈，正是 DNS 要避免的问题。"
  },
  {
    id: 14,
    lecture: "第二讲",
    topic: "DNS 资源记录",
    question: "在 DNS 资源记录中，type=A 通常表示什么？",
    options: ["主机名到 IPv4 地址的映射", "规范名的别名", "管理某域的权威域名服务器", "邮件服务器优先级"],
    answer: 0,
    source: "第二讲_应用层-(2)DNS、电子邮件.pptx · 第 39-40 页",
    detail: "课件列出 RR 格式和不同类型：A 记录中 name 是主机名，value 是 IPv4 地址；CNAME 是别名到规范名；NS 指向管理该域的域名服务器。"
  },
  {
    id: 15,
    lecture: "第二讲",
    topic: "电子邮件",
    question: "Alice 给 Bob 发送邮件时，Alice 的邮件服务器与 Bob 的邮件服务器之间通常使用哪种协议传送邮件？",
    options: ["SMTP", "POP3", "IMAP", "ARP"],
    answer: 0,
    source: "第二讲_应用层-(2)DNS、电子邮件.pptx · 第 52-56 页",
    detail: "SMTP 用于邮件传输代理之间转发邮件。POP3 和 IMAP 更多用于用户代理从邮箱中读取或管理邮件。"
  },
  {
    id: 16,
    lecture: "第三讲",
    topic: "UDP",
    question: "下列哪类应用最适合优先考虑 UDP？",
    options: ["容忍少量丢包但对时延敏感的应用", "必须保证字节流完全可靠且有序的文件传输", "需要内建拥塞控制的长连接下载", "必须由传输层自动重传全部丢包的支付系统"],
    answer: 0,
    source: "第三讲_传输层(1)基本概念、UDP.pptx · 第 19 页、第 28 页",
    detail: "UDP 没有连接建立延迟、首部开销小、协议处理简单，不进行拥塞控制和流量控制，因此常用于流媒体、DNS 等对时延敏感或请求响应简单的场景。"
  },
  {
    id: 17,
    lecture: "第三讲",
    topic: "UDP 校验和",
    question: "UDP 校验和的主要作用是什么？",
    options: ["检测 UDP 报文段在传输中是否出现差错", "为应用建立 TCP 连接", "决定路由器下一跳", "把域名解析为 IP 地址"],
    answer: 0,
    source: "第三讲_传输层(1)基本概念、UDP.pptx · 第 20-25 页",
    detail: "UDP 首部包含 checksum 字段。校验和用于差错检测，但不负责重传和可靠交付。"
  },
  {
    id: 18,
    lecture: "第三讲",
    topic: "可靠传输",
    question: "GBN 和 SR 的核心区别，哪一项说法正确？",
    options: ["GBN 累计确认并超时后重传多个未确认包，SR 对单个包分别确认和重传", "GBN 只能用于链路层，SR 只能用于 DNS", "SR 不需要序号，GBN 不需要 ACK", "二者都只能停止等待，不能流水线"],
    answer: 0,
    source: "第三讲_传输层(2)可靠传输.pptx · 第 52 页、第 57 页、第 72 页",
    detail: "回退 N 使用累计确认，接收方暂不确认非连续包，发送方超时后重传所有未确认包；选择重传为每个包单独确认，发送方只重传确认丢失或超时的包。"
  },
  {
    id: 19,
    lecture: "第三讲",
    topic: "TCP 可靠性",
    question: "TCP 快速重传通常由什么现象触发？",
    options: ["发送端收到多个重复 ACK", "应用进程关闭文件", "DNS 返回 CNAME", "MAC 地址发生冲突"],
    answer: 0,
    source: "第三讲_传输层(2)可靠传输.pptx · 第 88-89 页",
    detail: "快速重传是一种不必等待超时的重传优化。典型触发信号是接收端连续返回重复 ACK，暗示中间某个报文段可能丢失。"
  },
  {
    id: 20,
    lecture: "第三讲",
    topic: "TCP 连接",
    question: "TCP 使用三次握手建立连接，主要是为了什么？",
    options: ["让双方确认彼此收发能力并同步初始序号", "让 DNS 服务器返回 IP 地址", "让链路层计算 CRC", "为每台交换机配置 VLAN"],
    answer: 0,
    source: "第三讲_传输层(3)连接管理、流量与拥塞控制.pptx · 第 9-17 页",
    detail: "三次握手通过 SYN、SYN/ACK、ACK 让双方确认连接意愿、通信可达性和初始序号。课件也对比了两次握手可能带来的问题。"
  },
  {
    id: 21,
    lecture: "第三讲",
    topic: "流量控制",
    question: "TCP 流量控制主要解决什么问题？",
    options: ["防止发送方过快发送导致接收方缓存溢出", "选择自治系统之间的路由策略", "隐藏用户 Cookie", "检测以太网冲突"],
    answer: 0,
    source: "第三讲_传输层(3)连接管理、流量与拥塞控制.pptx · 第 26-36 页",
    detail: "流量控制关注接收端承受能力。TCP 通过接收窗口等机制让发送端不要超过接收方缓存和处理能力。"
  },
  {
    id: 22,
    lecture: "第三讲",
    topic: "拥塞控制",
    question: "网络拥塞最直接的后果通常不包括哪一项？",
    options: ["所有分组自动获得更低时延", "路由器缓存溢出导致丢包", "分组排队延迟增大", "大量资源用于重传或转发最终被丢弃的分组"],
    answer: 0,
    source: "第三讲_传输层(3)连接管理、流量与拥塞控制.pptx · 第 38-44 页",
    detail: "拥塞意味着进入网络的流量超过承载能力，常见表现是排队延迟增大、丢包、无效重传和资源浪费，不会自动降低时延。"
  },
  {
    id: 23,
    lecture: "第四讲",
    topic: "数据平面与控制平面",
    question: "网络层中，数据平面主要负责什么？",
    options: ["在单个路由器上把到达的数据报转发到正确输出接口", "全网范围内制定应用层 Cookie 策略", "生成 DNS 资源记录", "维护用户邮箱"],
    answer: 0,
    source: "第四讲_网络层(1)基本概念、路由器.pptx · 第 9-13 页",
    detail: "数据平面是单个路由器上的局部转发功能；控制平面负责路由功能，可能由传统分布式路由算法或 SDN 控制器实现。"
  },
  {
    id: 24,
    lecture: "第四讲",
    topic: "Internet 服务模型",
    question: "Internet 网络层的数据报服务通常被描述为哪种服务？",
    options: ["无连接、尽力而为", "面向连接、保证带宽", "保证按序且永不丢包", "只支持虚电路"],
    answer: 0,
    source: "第四讲_网络层(1)基本概念、路由器.pptx · 第 5-8 页",
    detail: "Internet 的 IP 层提供无连接的数据报服务，尽最大努力交付，但不承诺可靠性、顺序、带宽或时延。"
  },
  {
    id: 25,
    lecture: "第四讲",
    topic: "ARP",
    question: "ARP 的作用是什么？",
    options: ["在同一子网内根据 IP 地址获取对应 MAC 地址", "把 HTTP 请求转换成网页", "为 TCP 选择拥塞窗口", "把邮件从客户端发到服务器"],
    answer: 0,
    source: "第四讲_网络层(2)协议.pptx · 第 26-32 页",
    detail: "在子网内转发时，主机需要知道下一跳或目的主机的 MAC 地址。ARP 通过广播请求和单播响应完成 IP 到 MAC 的解析。"
  },
  {
    id: 26,
    lecture: "第四讲",
    topic: "DHCP",
    question: "DHCP 的主要功能是？",
    options: ["为主机动态分配 IP 地址等网络配置", "检测链路层帧的 CRC", "替代所有路由协议", "给 HTTP 响应设置 Cookie"],
    answer: 0,
    source: "第四讲_网络层(2)协议.pptx · 第 34-40 页",
    detail: "DHCP 用于让主机自动获得 IPv4 地址以及网关、DNS 等配置信息。课件给出了 DHCP 场景、架构和工作过程。"
  },
  {
    id: 27,
    lecture: "第四讲",
    topic: "NAT",
    question: "NAT 出方向转换中，通常会把私有源 IP 和源端口替换为什么？",
    options: ["NAT 设备的全局 IP 和新的端口号", "目的主机的 MAC 地址", "DNS 根服务器地址", "HTTP 状态码"],
    answer: 0,
    source: "第四讲_网络层(2)协议.pptx · 第 43-45 页",
    detail: "外出数据报经过 NAT 时，源私有 IP 和端口会被替换成 NAT 的公网 IP 和新端口，并在 NAT 转换表中记录映射关系。"
  },
  {
    id: 28,
    lecture: "第四讲",
    topic: "路由算法",
    question: "链路状态算法与距离向量算法的一个重要区别是？",
    options: ["链路状态算法需要全局拓扑信息，距离向量算法主要依赖邻居交换信息", "链路状态算法不能计算最短路", "距离向量算法要求每个节点知道全网拓扑", "二者都只用于应用层协议"],
    answer: 0,
    source: "第四讲_网络层(3)路由技术(1).pptx · 第 10-11 页、第 16-19 页、第 31-35 页",
    detail: "链路状态算法基于全局拓扑和链路开销，常结合 Dijkstra；距离向量算法更局部、分布式，各节点与邻居交换距离向量并迭代更新。"
  },
  {
    id: 29,
    lecture: "第五讲",
    topic: "数据链路层",
    question: "数据链路层负责的典型功能不包括哪一项？",
    options: ["端到端进程间可靠字节流", "成帧", "差错检测与纠正", "链路复用和访问控制"],
    answer: 0,
    source: "第五讲_链路层(1)概述、成帧、差错检测、访问控制.pptx · 第 3-9 页",
    detail: "链路层处理单跳链路上的帧传输，提供成帧、差错检测/纠正、介质访问控制等服务。端到端进程间可靠字节流更接近 TCP 的职责。"
  },
  {
    id: 30,
    lecture: "第五讲",
    topic: "CRC",
    question: "CRC 校验中，发送端在原始数据后追加的校验码来自什么？",
    options: ["用生成多项式对补零后的数据做模 2 除得到的余数", "随机生成的一串比特", "目的主机的 IP 地址", "HTTP 响应状态码"],
    answer: 0,
    source: "第五讲_链路层(1)概述、成帧、差错检测、访问控制.pptx · 第 29 页、第 33-35 页",
    detail: "CRC 先选定生成多项式 G，把数据 D 乘以 2^r 后用 G 做模 2 除，得到 r 位余数 R，R 就是要附加的 CRC 校验码。"
  },
  {
    id: 31,
    lecture: "第五讲",
    topic: "CSMA",
    question: "CSMA 的核心思想是什么？",
    options: ["先侦听信道，空闲再发送", "不听信道，任何时候都直接发送", "每个站点固定分配独占频段", "只允许中心服务器发送帧"],
    answer: 0,
    source: "第五讲_链路层(1)概述、成帧、差错检测、访问控制.pptx · 第 87-90 页",
    detail: "CSMA 即载波侦听多路访问，特点是“先听后发”。如果信道忙则推迟发送，不同版本在等待策略上有所差别。"
  },
  {
    id: 32,
    lecture: "第五讲",
    topic: "有线与无线访问控制",
    question: "关于以太网和 802.11 WiFi 的访问控制，哪一项符合课件总结？",
    options: ["以太网常用 CSMA/CD，802.11 WiFi 常用 CSMA/CA", "二者都完全不需要处理冲突", "WiFi 因无线信道更容易做冲突检测，所以使用 CSMA/CD", "以太网只能用轮流协议"],
    answer: 0,
    source: "第五讲_链路层(1)概述、成帧、差错检测、访问控制.pptx · 第 114-115 页；第五讲_链路层(3)无线网络.pptx · 第 29-30 页",
    detail: "有线信道中冲突检测相对容易，以太网使用 CSMA/CD；无线环境中冲突检测困难，802.11 使用以冲突避免为核心的 CSMA/CA。"
  },
  {
    id: 33,
    lecture: "第五讲",
    topic: "MAC 地址",
    question: "MAC 地址在局域网中的主要用途是？",
    options: ["标识物理相连网络接口之间收发帧的地址", "作为 DNS 域名的别名", "决定 TCP 拥塞窗口大小", "表示应用层端口号"],
    answer: 0,
    source: "第五讲_链路层(2)有线局域网.pptx · 第 3-6 页",
    detail: "课件区分 IP 地址和 MAC 地址：IP 地址用于网络层转发，MAC 地址用于物理相连的网络接口之间收发链路层帧。"
  },
  {
    id: 34,
    lecture: "第五讲",
    topic: "VLAN",
    question: "配置 VLAN 的一个直接效果是？",
    options: ["在同一套物理交换机上划分多个独立广播域", "让所有端口强制处于同一广播域", "取消 MAC 地址学习", "替代 TCP 三次握手"],
    answer: 0,
    source: "第五讲_链路层(2)有线局域网.pptx · 第 59-64 页",
    detail: "VLAN 可以在一套物理交换机设备上运行多个虚拟局域网，每个 VLAN 是单独的广播域，常见方式包括基于端口和基于 MAC 地址的 VLAN。"
  },
  {
    id: 35,
    lecture: "第五讲",
    topic: "无线网络",
    question: "在 802.11 无线网络中，主机发送或接收网络层数据前通常需要先做什么？",
    options: ["与某个 AP 关联", "向所有交换机发送 VLAN 标签", "执行 TCP 快速重传", "修改 DNS 根记录"],
    answer: 0,
    source: "第五讲_链路层(3)无线网络.pptx · 第 24-30 页",
    detail: "课件说明无线主机在传输网络层数据之前需要与 AP 关联。AP 会周期性发送信标帧，主机据此选择并完成关联。"
  },
  {
    id: 36,
    lecture: "第一讲",
    topic: "电路交换",
    question: "与分组交换相比，电路交换的典型特点是什么？",
    options: ["通信前建立连接并预留端到端资源", "每个分组独立携带首部并竞争链路", "不需要任何连接建立过程", "只适用于无线局域网"],
    answer: 0,
    source: "第一讲_(2) 网络基础知识.pptx · 第 42-47 页",
    detail: "电路交换先呼叫建立连接，预留链路带宽和交换能力；连接建立后，通信双方独占这条物理通路。分组交换则更适合突发数据共享链路。"
  },
  {
    id: 37,
    lecture: "第一讲",
    topic: "网络核心",
    question: "网络核心通常由哪些设备和资源构成？",
    options: ["路由器和通信链路组成的网状网络", "只包含用户浏览器", "只包含 DNS 根服务器", "只包含终端上的应用进程"],
    answer: 0,
    source: "第一讲_(2) 网络基础知识.pptx · 第 6-8 页",
    detail: "课件把网络核心描述为由路由器、通信链路构成的网状网络，负责在互联网络中转发数据。"
  },
  {
    id: 38,
    lecture: "第一讲",
    topic: "RTT",
    question: "RTT 指的是什么？",
    options: ["从发送方发送数据开始，到收到接收方确认所经历的往返时间", "单个比特写入链路所需时间", "路由表中下一跳数量", "链路层帧的最大长度"],
    answer: 0,
    source: "第一讲_(2) 网络基础知识.pptx · 第 69 页",
    detail: "RTT 即 Round-Trip Time，可用于判断网络通断、测试网络时延、估计丢包等，是端到端路径上的往返时间。"
  },
  {
    id: 39,
    lecture: "第一讲",
    topic: "时延带宽积",
    question: "时延带宽积可以理解为什么？",
    options: ["链路中在途的比特数量规模", "一个路由器的端口数量", "DNS 缓存条目数量", "TCP 首部校验和长度"],
    answer: 0,
    source: "第一讲_(2) 网络基础知识.pptx · 第 70 页",
    detail: "时延带宽积 = 传播时延 × 带宽。若发送端持续发送，在第一个 bit 即将到达终点时，链路上已经有相当于时延带宽积的比特在途。"
  },
  {
    id: 40,
    lecture: "第一讲",
    topic: "分层模型",
    question: "TCP/IP 参考模型中，负责通过多跳连接把数据包传至目的地的是哪一层？",
    options: ["互联网层", "表示层", "会话层", "物理层"],
    answer: 0,
    source: "第一讲_(2) 网络基础知识.pptx · 第 93-101 页",
    detail: "TCP/IP 模型中的互联网层定义数据包格式和协议，通过多跳连接完成主机间传输；典型协议包括 IPv4、IPv6 等。"
  },
  {
    id: 41,
    lecture: "第二讲",
    topic: "Socket",
    question: "应用进程通常通过什么接口向传输层发送和接收消息？",
    options: ["Socket", "ARP 表", "CRC 生成多项式", "交换机转发表"],
    answer: 0,
    source: "第二讲_应用层-(1)Web与HTTP.pptx · 第 6 页、第 11 页",
    detail: "应用层运行在端系统进程中，进程通过 socket 与传输层交互。Socket 可以理解为应用进程通向网络的一扇门。"
  },
  {
    id: 42,
    lecture: "第二讲",
    topic: "HTTP 状态码",
    question: "HTTP 状态码中，4xx 通常表示什么？",
    options: ["客户端差错", "服务器永久成功", "DNS 权威回答", "链路层冲突"],
    answer: 0,
    source: "第二讲_应用层-(1)Web与HTTP.pptx · 第 61-63 页",
    detail: "HTTP 状态码是三位数字。课件中 4xx 表示客户的差错，例如请求有错误、资源不存在或权限不足等。"
  },
  {
    id: 43,
    lecture: "第二讲",
    topic: "Web 缓存",
    question: "代理服务器缓存 Web 页副本的主要目标是什么？",
    options: ["尽量减少原始服务器参与并降低访问时延", "让浏览器不能访问任何动态页面", "替代 TCP 的可靠传输", "检测以太网帧错误"],
    answer: 0,
    source: "第二讲_应用层-(1)Web与HTTP.pptx · 第 64-70 页",
    detail: "Web 代理缓存保存已访问资源的副本，使浏览器可从代理服务器获取页面，减少原始服务器负载和跨网络传输时延。"
  },
  {
    id: 44,
    lecture: "第二讲",
    topic: "DNS 隐私与安全",
    question: "DNSSEC 主要试图解决 DNS 的哪类问题？",
    options: ["认证 DNS 响应，降低伪造与篡改风险", "让 UDP 自动变成可靠传输", "为所有网页内容加缓存", "为无线主机选择 AP"],
    answer: 0,
    source: "第二讲_应用层-(2)DNS、电子邮件.pptx · 第 44-49 页",
    detail: "课件在 DNS 脆弱性后介绍 DNSSEC。DNSSEC 通过签名和信任链等机制验证 DNS 数据的真实性，重点是认证而非隐藏所有查询内容。"
  },
  {
    id: 45,
    lecture: "第二讲",
    topic: "POP3",
    question: "POP3 的三个阶段通常包括什么？",
    options: ["认证、事务处理、更新", "握手、拥塞避免、快速恢复", "成帧、检错、退避", "广播、学习、转发"],
    answer: 0,
    source: "第二讲_应用层-(2)DNS、电子邮件.pptx · 第 69-71 页",
    detail: "POP3 是一个简单的最终交付协议。用户代理连接服务器后，经历认证阶段、事务处理阶段和更新阶段。"
  },
  {
    id: 46,
    lecture: "第三讲",
    topic: "复用与分用",
    question: "传输层的分用主要依赖什么信息把报文段交给正确应用进程？",
    options: ["套接字标识与端口号", "CRC 多项式", "VLAN 端口组", "无线信道编号"],
    answer: 0,
    source: "第三讲_传输层(1)基本概念、UDP.pptx · 第 8-17 页",
    detail: "同一主机上可能有多个应用进程和多个 socket。传输层利用端口号、IP 地址和协议等信息完成复用与分用。"
  },
  {
    id: 47,
    lecture: "第三讲",
    topic: "流水线传输",
    question: "相对停止等待协议，流水线传输的核心改进是什么？",
    options: ["允许发送方同时有多个未确认分组在途", "取消所有序号", "要求每次只能发送一个分组", "只在链路层工作"],
    answer: 0,
    source: "第三讲_传输层(2)可靠传输.pptx · 第 50-57 页",
    detail: "停止等待在长肥网络中效率低。流水线允许多个分组未确认时继续发送，因此需要更大的序号空间、缓存未确认分组并处理多包丢失。"
  },
  {
    id: 48,
    lecture: "第三讲",
    topic: "超时估计",
    question: "Karn 算法主要是为了解决 TCP 中什么问题？",
    options: ["重传包 ACK 的二义性导致 RTT 样本难以判断", "无法获得 MAC 地址", "DNS 资源记录过期", "VLAN 广播域太多"],
    answer: 0,
    source: "第三讲_传输层(2)可靠传输.pptx · 第 83-87 页",
    detail: "TCP 重传后收到 ACK 时，发送端难以判断 ACK 对应原包还是重传包，这会影响 RTT 估计。Karn 算法用于处理这种确认二义性。"
  },
  {
    id: 49,
    lecture: "第三讲",
    topic: "慢启动",
    question: "TCP 慢启动阶段通常如何增大发送速率？",
    options: ["从较小拥塞窗口开始，随 ACK 到来快速增长", "一直保持 cwnd 为 0", "每次丢包后把窗口加倍", "由 DNS 服务器指定窗口大小"],
    answer: 0,
    source: "第三讲_传输层(3)连接管理、流量与拥塞控制.pptx · 第 43-44 页；第三讲_传输层(4)新型拥塞控制.pptx · 第 10 页",
    detail: "慢启动用于新建连接或拥塞后探测可用容量。它从较小 cwnd 开始，随确认到来快速增加窗口，直到进入拥塞避免或遇到拥塞信号。"
  },
  {
    id: 50,
    lecture: "第三讲",
    topic: "QUIC",
    question: "课件中 QUIC 的一个重要部署优势是什么？",
    options: ["在用户态实现，更容易随应用快速迭代", "必须修改所有路由器硬件才能使用", "完全不使用加密", "只能在以太网上工作"],
    answer: 0,
    source: "第三讲_传输层(5)新型传输层协议.pptx · 第 24-33 页",
    detail: "课件指出 QUIC 基于 UDP，并融合 TCP/TLS/HTTP 特性。它在用户态实现，与操作系统内核解耦，更便于部署和更新。"
  },
  {
    id: 51,
    lecture: "第四讲",
    topic: "IPv4 分片",
    question: "IPv4 数据报分片通常发生在什么情况下？",
    options: ["数据报长度超过下一跳链路 MTU", "HTTP 状态码为 404", "DNS 返回 A 记录", "TCP 收到重复 ACK"],
    answer: 0,
    source: "第四讲_网络层(2)协议.pptx · 第 4-9 页",
    detail: "IPv4 数据报需要适配不同链路的 MTU。当数据报过大时，网络层可能进行分片，并在目的端重组。"
  },
  {
    id: 52,
    lecture: "第四讲",
    topic: "CIDR",
    question: "CIDR 地址聚合的主要意义是什么？",
    options: ["用更灵活的前缀聚合减少路由表规模", "把 MAC 地址改成 128 位", "替代所有传输层端口", "让 HTTP 支持 Cookie"],
    answer: 0,
    source: "第四讲_网络层(2)协议.pptx · 第 12-20 页",
    detail: "CIDR 使用无类别前缀表示法，能够把多个连续地址块聚合成较短前缀，减少路由表项数量并提升转发可扩展性。"
  },
  {
    id: 53,
    lecture: "第四讲",
    topic: "ICMP",
    question: "ICMP 在网络层中的典型用途是？",
    options: ["报告差错和提供网络诊断信息", "发送电子邮件正文", "计算 CRC 校验码", "在浏览器中保存 Cookie"],
    answer: 0,
    source: "第四讲_网络层(2)协议.pptx · 第 50 页",
    detail: "ICMP 报文类型用于网络层控制和诊断，例如目的不可达、超时、回显请求/应答等。"
  },
  {
    id: 54,
    lecture: "第四讲",
    topic: "SDN",
    question: "SDN 的核心思想更接近哪一项？",
    options: ["将控制逻辑相对集中，由控制器计算并下发转发规则", "让每台主机只运行 POP3", "取消数据平面转发功能", "把所有帧都广播到全网"],
    answer: 0,
    source: "第四讲_网络层(1)基本概念、路由器.pptx · 第 10-13 页；第四讲_网络层(4)软件定义网络.pptx · 第 12-17 页",
    detail: "SDN 把控制平面逻辑集中到控制器，路由器或交换机主要执行数据平面的转发规则。控制器逻辑上集中，物理上可由集群实现。"
  },
  {
    id: 55,
    lecture: "第四讲",
    topic: "IPv6",
    question: "IPv6 相比 IPv4 的一个最直接变化是？",
    options: ["地址长度从 32 位扩展到 128 位", "完全取消网络层", "只能承载 UDP，不能承载 TCP", "把 MAC 地址改成 16 位"],
    answer: 0,
    source: "第四讲_网络层(5)网络层增强技术.pptx · 第 3-12 页",
    detail: "IPv6 采用 128 位地址空间，并调整了头部和相关 ICMP、路由、迁移机制。它并不是取消网络层或只支持某一种传输层协议。"
  },
  {
    id: 56,
    lecture: "第五讲",
    topic: "成帧",
    question: "链路层“成帧”的主要目的是什么？",
    options: ["把比特流划分成可识别的数据帧", "把域名转换为 IP 地址", "建立 TCP 三次握手", "选择自治系统间路由策略"],
    answer: 0,
    source: "第五讲_链路层(1)概述、成帧、差错检测、访问控制.pptx · 第 10-22 页",
    detail: "物理层看到的是连续比特流，链路层需要通过长度计数、定界符、比特填充等方式识别一帧从哪里开始、到哪里结束。"
  },
  {
    id: 57,
    lecture: "第五讲",
    topic: "差错检测",
    question: "下列哪一种检错码在数据链路层中广泛使用？",
    options: ["循环冗余校验 CRC", "HTTP Cookie", "DNS CNAME", "TCP 三次握手"],
    answer: 0,
    source: "第五讲_链路层(1)概述、成帧、差错检测、访问控制.pptx · 第 29-35 页",
    detail: "课件列出奇偶校验、校验和、CRC 等检错码，其中 CRC 是数据链路层广泛使用的校验方法，以太网和无线局域网常用 CRC-32。"
  },
  {
    id: 58,
    lecture: "第五讲",
    topic: "以太网帧",
    question: "以太网帧中的地址字段通常是什么地址？",
    options: ["目的 MAC 地址和源 MAC 地址", "目的 URL 和源 URL", "DNS 事务 ID 和 TTL", "TCP 拥塞窗口和接收窗口"],
    answer: 0,
    source: "第五讲_链路层(2)有线局域网.pptx · 第 20-30 页",
    detail: "以太网是链路层协议，帧头中使用 MAC 地址标识同一链路或局域网内的发送方和接收方，而不是 URL 或 TCP 窗口。"
  },
  {
    id: 59,
    lecture: "第五讲",
    topic: "交换机学习",
    question: "数据链路层交换机通常如何学习转发表？",
    options: ["根据收到帧的源 MAC 地址和入端口建立映射", "根据 HTTP 响应正文学习", "通过 DNSSEC 签名学习", "由 TCP 慢启动计算"],
    answer: 0,
    source: "第五讲_链路层(2)有线局域网.pptx · 第 50 页附近",
    detail: "交换机处理数据帧时，会观察帧的源 MAC 地址来自哪个端口，并据此更新交换表；后续看到目的 MAC 时即可定向转发。"
  },
  {
    id: 60,
    lecture: "第五讲",
    topic: "无线链路",
    question: "为什么无线网络中冲突检测比有线网络更困难？",
    options: ["无线发送时本机信号强，且存在隐藏终端等问题", "无线链路没有任何噪声", "无线网络不需要共享介质", "所有无线主机都能完全同时听到彼此"],
    answer: 0,
    source: "第五讲_链路层(1)概述、成帧、差错检测、访问控制.pptx · 第 114 页；第五讲_链路层(3)无线网络.pptx · 第 8-30 页",
    detail: "无线信道存在衰减、干扰、隐藏终端等特征，发送端也难以一边强发送一边准确检测其他弱信号，因此 802.11 更强调冲突避免而非冲突检测。"
  },
  {
    id: "org-1",
    course: "org",
    lecture: "课程概述",
    topic: "ENIAC",
    question: "课件中把哪台机器称为世界上第一台电子计算机？",
    options: ["ENIAC", "IBM PC 5150", "Intel 4004", "Altair 8800"],
    answer: 0,
    source: "xid-10879755_1.pdf · 第 5 页",
    detail: "ENIAC 于 1946 年在宾夕法尼亚大学诞生，课件列出其性能、电子管数量、功率、占地和重量等信息。"
  },
  {
    id: "org-2",
    course: "org",
    lecture: "课程概述",
    topic: "冯·诺依曼",
    question: "冯·诺依曼结构最核心的思想之一是什么？",
    options: ["程序和数据都以二进制形式存放在存储器中", "程序只能存放在外部纸带上", "CPU 不需要控制器", "输入输出设备必须和运算器合并"],
    answer: 0,
    source: "xid-10879755_1.pdf · 第 8 页；xid-10908613_1.pdf · 第 4 页",
    detail: "课件强调数据和程序不加区别地以二进制代码形式存放在存储器中，并由地址指定位置，这是存储程序思想的重要基础。"
  },
  {
    id: "org-3",
    course: "org",
    lecture: "课程概述",
    topic: "微处理器",
    question: "课件中提到 Intel 4004 是哪一类早期微处理器？",
    options: ["4 位微处理器", "16 位微处理器", "32 位微处理器", "64 位微处理器"],
    answer: 0,
    source: "xid-10879755_1.pdf · 第 65 页",
    detail: "课件在微处理器兴起部分列出：1971 年 Intel 4004 为 4 位，1972 年 8008 为 8 位，1978 年 8086 为 16 位。"
  },
  {
    id: "org-4",
    course: "org",
    lecture: "基本结构",
    topic: "五大部件",
    question: "冯·诺依曼计算机的五大组成部分不包括哪一项？",
    options: ["路由器", "运算器", "控制器", "存储器"],
    answer: 0,
    source: "xid-10908613_1.pdf · 第 4-5 页",
    detail: "五大部分是运算器、控制器、存储器、输入设备和输出设备。路由器是计算机网络设备，不属于该五大部件。"
  },
  {
    id: "org-5",
    course: "org",
    lecture: "基本结构",
    topic: "自动执行",
    question: "冯·诺依曼结构中，计算机工作时会自动从哪里取出指令并执行？",
    options: ["存储器", "显示器", "键盘", "电源模块"],
    answer: 0,
    source: "xid-10908613_1.pdf · 第 4 页",
    detail: "课件把“自动地从存储器中取出指令加以执行”列为冯·诺依曼结构要点之一。"
  },
  {
    id: "org-6",
    course: "org",
    lecture: "基本结构",
    topic: "汇编语言",
    question: "汇编语言通常可以看作什么？",
    options: ["机器语言的符号化描述", "高级语言的自动垃圾回收机制", "操作系统内核调度算法", "数据库查询语言"],
    answer: 0,
    source: "xid-10908613_1.pdf · 第 7-8 页",
    detail: "课件将汇编语言描述为较低级的程序设计语言，主要是机器语言的符号化描述，通常针对特定计算机或计算机系列设计。"
  },
  {
    id: "org-7",
    course: "org",
    lecture: "基本结构",
    topic: "CISC/RISC",
    question: "CISC 的英文含义是什么？",
    options: ["Complex Instruction Set Computer", "Central Interrupt Service Controller", "Cache Integrated Storage Core", "Compact Internal Signal Channel"],
    answer: 0,
    source: "xid-10908613_1.pdf · 第 25 页、第 29 页",
    detail: "CISC 是复杂指令系统计算机，RISC 是精简指令系统计算机。课件把二者作为体系结构之争的基本概念。"
  },
  {
    id: "org-8",
    course: "org",
    lecture: "x86/CISC",
    topic: "兼容性",
    question: "x86 指令系统长期发展的一个重要特点是什么？",
    options: ["强调向前兼容，后续处理器包含早期处理器的指令和操作方式", "完全删除早期指令以简化硬件", "只能运行 64 位程序", "不允许增加新指令"],
    answer: 0,
    source: "xid-10966019_1.pdf · 第 4 页",
    detail: "课件指出每款处理器包含该系列早期处理器的全部指令、寄存器和操作方式，同时还会增强和扩充指令系统。"
  },
  {
    id: "org-9",
    course: "org",
    lecture: "x86/CISC",
    topic: "8086",
    question: "Intel 8086 对外地址线数量和可寻址空间分别是？",
    options: ["20 根地址线，1MB 空间", "16 根地址线，64KB 空间", "32 根地址线，4GB 空间", "8 根地址线，256B 空间"],
    answer: 0,
    source: "xid-10966019_1.pdf · 第 5 页",
    detail: "8086 内部通用寄存器为 16 位，对外有 16 根数据线和 20 根地址线，可寻址空间为 2^20 字节，即 1MB。"
  },
  {
    id: "org-10",
    course: "org",
    lecture: "x86/CISC",
    topic: "8088",
    question: "Intel 8088 相比 8086 的主要简化是什么？",
    options: ["数据总线只有 8 位宽", "完全不支持 x86 指令", "地址线减少到 8 根", "不能访问内存"],
    answer: 0,
    source: "xid-10966019_1.pdf · 第 6 页",
    detail: "课件介绍 IBM PC 使用的 Intel 8088 是 8086 的简化版本，主要区别是数据总线只有 8 位宽。"
  },
  {
    id: "org-11",
    course: "org",
    lecture: "x86/CISC",
    topic: "x86-64",
    question: "AMD Opteron 在 x86 发展中的重要意义是？",
    options: ["第一款将 x86 扩展到 64 位的微处理器", "第一款 4 位微处理器", "第一款完全不兼容 32 位程序的 x86", "第一款无线网络处理器"],
    answer: 0,
    source: "xid-10966019_1.pdf · 第 8 页",
    detail: "课件指出 AMD Opteron 是 x86 扩展到 64 位的第一款微处理器，可以访问高于 4GB 的存储器，并兼容 32 位 x86 程序。"
  },
  {
    id: "org-12",
    course: "org",
    lecture: "x86/CISC",
    topic: "运行模式",
    question: "x86-64 的长模式包含哪两种运行子模式？",
    options: ["64 位模式和兼容模式", "实模式和虚拟 8086 模式", "用户模式和内核模式", "流水模式和总线模式"],
    answer: 0,
    source: "xid-10966019_1.pdf · 第 9 页",
    detail: "课件表格中列出长模式 Long mode 包括 64-bit mode 和 Compatibility mode，后者可支持已有程序不重新编译。"
  },
  {
    id: "org-13",
    course: "org",
    lecture: "MIPS/RISC",
    topic: "RISC 思想",
    question: "MIPS 的设计指导思想更接近哪一项？",
    options: ["减少指令类型、降低指令复杂度", "让每条指令尽可能包含多个复杂操作", "完全取消寄存器", "只使用变长复杂编码"],
    answer: 0,
    source: "xid-11112842_1.pdf · 第 8 页",
    detail: "MIPS 全称 Microprocessor without Interlocked Piped Stages，课件强调其基本原则是 A simpler CPU is a faster CPU。"
  },
  {
    id: "org-14",
    course: "org",
    lecture: "MIPS/RISC",
    topic: "图灵奖",
    question: "课件中提到 2017 年图灵奖表彰 Patterson 和 Hennessy 的主要贡献领域是？",
    options: ["计算机体系结构的系统化、定量设计与评价方法", "操作系统文件系统命名", "网页浏览器设计", "数据库事务隔离"],
    answer: 0,
    source: "xid-11112842_1.pdf · 第 4-5 页",
    detail: "Patterson 和 Hennessy 是 RISC 与计算机体系结构领域的重要人物，课件引用了图灵奖对其体系结构方法论贡献的表彰。"
  },
  {
    id: "org-15",
    course: "org",
    lecture: "MIPS/RISC",
    topic: "RISC-V 格式",
    question: "RISC-V 中 R 型指令主要对应哪类操作？",
    options: ["寄存器-寄存器操作", "长立即数操作", "访存 store 操作", "无条件跳转操作"],
    answer: 0,
    source: "xid-11112842_1.pdf · 第 54 页",
    detail: "课件列出 RISC-V 指令格式：R 型为寄存器-寄存器操作，I 型为短立即数和 load，S 型为 store，B/J 为跳转相关。"
  },
  {
    id: "org-16",
    course: "org",
    lecture: "数字电路",
    topic: "布尔代数",
    question: "布尔代数的基本思想中，两个元素通常指什么？",
    options: ["真和假", "高电压和低电压的具体数值", "输入和输出设备", "CPU 和内存"],
    answer: 0,
    source: "xid-11112843_1.pdf · 第 6 页",
    detail: "课件介绍布尔代数的基本思想：两个元素是真、假；三种基本运算是与、或、非。"
  },
  {
    id: "org-17",
    course: "org",
    lecture: "数字电路",
    topic: "香农",
    question: "香农关于开关电路的主要贡献是什么？",
    options: ["用电子开关模拟布尔逻辑运算，奠定数字电路设计理论基础", "提出 TCP/IP 协议", "设计第一台 IBM PC", "发明 HTTP Cookie"],
    answer: 0,
    source: "xid-11112843_1.pdf · 第 7 页",
    detail: "课件指出香农在硕士论文中用电子开关模拟布尔逻辑运算，建立了数字电路设计的理论基础。"
  },
  {
    id: "org-18",
    course: "org",
    lecture: "数字电路",
    topic: "门电路",
    question: "布尔代数中的与、或、非运算在课件中被说明可以转换为什么形式？",
    options: ["与非或者或非运算", "十进制加法", "网络路由表", "磁盘文件目录"],
    answer: 0,
    source: "xid-11112843_1.pdf · 第 6 页",
    detail: "课件提到与、或、非这三种运算又都可以转换成与非或者或非运算，这也是门电路实现中的常见基础。"
  },
  {
    id: "org-19",
    course: "org",
    lecture: "运算部件",
    topic: "乘法器",
    question: "课件中 N 位乘法器的基本流程首先检查什么？",
    options: ["乘数寄存器的最低位", "程序计数器最高位", "总线仲裁信号", "中断向量表"],
    answer: 0,
    source: "xid-11241477_1.pdf · 第 4-6 页",
    detail: "乘法器工作流程从检查乘数寄存器最低位开始，若最低位为 1，则把被乘数寄存器和乘积寄存器内容相加。"
  },
  {
    id: "org-20",
    course: "org",
    lecture: "运算部件",
    topic: "移位",
    question: "在乘法器的常见实现流程中，被乘数和乘数通常如何移动？",
    options: ["被乘数左移，乘数右移", "被乘数右移，乘数左移", "二者都只左移", "二者都不移动"],
    answer: 0,
    source: "xid-11241477_1.pdf · 第 4-6 页",
    detail: "课件流程图中，若完成最低位检查后，会将被乘数寄存器左移一位、乘数寄存器右移一位，并循环 N 次。"
  },
  {
    id: "org-21",
    course: "org",
    lecture: "控制器",
    topic: "控制器任务",
    question: "控制器在冯·诺依曼结构中的基本任务是什么？",
    options: ["按指令每一步操作需要发出特定命令信号", "长期保存用户文件", "显示图像像素", "直接替代所有外设"],
    answer: 0,
    source: "xid-11241478_1.pdf · 第 4 页",
    detail: "课件指出控制器的基本任务是根据指令各步骤的需要，向相关部件发出特定控制命令信号。"
  },
  {
    id: "org-22",
    course: "org",
    lecture: "控制器",
    topic: "指令系统",
    question: "课件假想计算机中的 LOAD R, M 指令功能是？",
    options: ["将 M 中的内容装入 R", "将 R 的内容存入 M", "无条件转向 L", "将 R 与 M 相加后存入 M"],
    answer: 0,
    source: "xid-11241478_1.pdf · 第 5-7 页",
    detail: "课件给出假想指令系统：LOAD R,M 将 M 中内容装入 R；STORE M,R 将 R 内容存入 M；JMP L 为无条件转移。"
  },
  {
    id: "org-23",
    course: "org",
    lecture: "控制器",
    topic: "控制器分类",
    question: "硬布线控制器和微程序控制器的主要区别通常在于什么？",
    options: ["控制信号产生方式不同", "一个用于网络层一个用于应用层", "一个只能显示图像一个只能播放声音", "二者没有任何区别"],
    answer: 0,
    source: "xid-11241478_1.pdf · 第 2-3 页、第 27 页",
    detail: "该讲主题是控制器基本原理、硬布线控制器和微程序控制器。二者核心差别在于控制逻辑与控制信号的组织和产生方式。"
  },
  {
    id: "org-24",
    course: "org",
    lecture: "流水线",
    topic: "五级流水",
    question: "课件中 80486 的五级流水线包含的阶段不包括哪一项？",
    options: ["DNS 解析", "取指", "译码", "回写"],
    answer: 0,
    source: "xid-11396528_1.pdf · 第 5 页",
    detail: "课件列出 486 的五级流水线：取指、译码、地址生成、执行、回写。DNS 解析是网络应用层相关概念。"
  },
  {
    id: "org-25",
    course: "org",
    lecture: "流水线",
    topic: "超标量",
    question: "Pentium 的超标量流水线中，U 流水和 V 流水体现了什么思想？",
    options: ["双发射，多个执行流水并行工作", "只能一次执行半条指令", "完全取消译码阶段", "只支持串行 I/O"],
    answer: 0,
    source: "xid-11396528_1.pdf · 第 6 页",
    detail: "课件说明 Pentium 是第一款超标量流水线 x86 CPU，具有 U 流水和 V 流水，支持双发射。"
  },
  {
    id: "org-26",
    course: "org",
    lecture: "流水线",
    topic: "微操作",
    question: "Pentium Pro 的流水线会把复杂 x86 指令拆分成什么？",
    options: ["简单微操作（μop）", "DNS 查询报文", "VLAN 标签", "外设模拟信号"],
    answer: 0,
    source: "xid-11396528_1.pdf · 第 8 页",
    detail: "课件指出 Pentium Pro 会将复杂的 x86 指令拆分成简单微指令或微操作，这是现代 x86 处理器的重要实现思路。"
  },
  {
    id: "org-27",
    course: "org",
    lecture: "流水线",
    topic: "转移预测",
    question: "转移预测技术主要是为了缓解哪类指令对流水线的影响？",
    options: ["分支/转移指令", "普通加法指令", "简单寄存器传送", "无条件数据缓存读写"],
    answer: 0,
    source: "xid-11396528_1.pdf · 第 2-3 页、第 37 页",
    detail: "该讲重点分析转移指令对流水线的影响，并介绍转移预测、BTB 和返回地址栈等优化技术。"
  },
  {
    id: "org-28",
    course: "org",
    lecture: "中断异常",
    topic: "异常",
    question: "课件中 UNIVAC 的异常处理起源例子关注哪种情况？",
    options: ["算术运算溢出", "HTTP 请求超时", "无线信道冲突", "DNS 缓存过期"],
    answer: 0,
    source: "xid-11400182_1.pdf · 第 5-7 页",
    detail: "课件提到 UNIVAC 在算术运算溢出时可转向地址 0 执行修复指令或停机，是早期异常处理的例子。"
  },
  {
    id: "org-29",
    course: "org",
    lecture: "中断异常",
    topic: "中断/异常",
    question: "CPU 遇到需要特殊处理的事件时，一般会怎样？",
    options: ["强行中止当前程序，启动相应处理程序，处理后恢复原程序", "立即删除所有内存", "只修改显示器亮度", "必须重装操作系统"],
    answer: 0,
    source: "xid-11400182_1.pdf · 第 8 页",
    detail: "课件定义中断或异常为系统外部、内部或现行程序本身出现需特殊处理的事件，CPU 会中止当前程序并转入相应处理。"
  },
  {
    id: "org-30",
    course: "org",
    lecture: "中断异常",
    topic: "外部中断",
    question: "外部中断的典型来源更接近哪一项？",
    options: ["I/O 设备发出的请求或信号", "普通加法结果正确完成", "网页中的 CSS 文件", "DNS 资源记录 TTL"],
    answer: 0,
    source: "xid-11400182_1.pdf · 第 6-8 页",
    detail: "课件中 DYSEAC 的外部中断例子来自 I/O 信号。外部中断通常与设备、定时器等 CPU 外部事件有关。"
  },
  {
    id: "org-31",
    course: "org",
    lecture: "输入输出",
    topic: "I/O 接口",
    question: "现代微型计算机中设置 I/O 接口电路的主要原因是什么？",
    options: ["CPU 和外设速度差异大，外设信息格式和信号形式多样", "让 CPU 不再需要执行指令", "替代所有主存储器", "让所有设备只能串行工作"],
    answer: 0,
    source: "xid-11453534_1.pdf · 第 8 页",
    detail: "课件指出 CPU 与外设速度差距大，外设信息格式和接口信号形式多样，因此需要 I/O 接口作为 CPU 与外设之间的数据转接站。"
  },
  {
    id: "org-32",
    course: "org",
    lecture: "输入输出",
    topic: "Altair 8800",
    question: "课件中 Altair 8800 面板上的简单输入和输出分别是什么？",
    options: ["手动开关和小灯泡", "键盘和高清显示器", "摄像头和扬声器", "无线网卡和路由器"],
    answer: 0,
    source: "xid-11453534_1.pdf · 第 4 页",
    detail: "课件介绍第一台微型计算机 Altair 8800，面板上提供简单输入输出：输入是手动开关，输出是小灯泡。"
  },
  {
    id: "org-33",
    course: "org",
    lecture: "输入输出",
    topic: "并行/串行",
    question: "I/O 接口中“串行”和“并行”的区别主要涉及什么？",
    options: ["数据传输位的组织方式", "CPU 是否使用二进制", "程序是否存储在内存", "网页是否使用 HTTPS"],
    answer: 0,
    source: "xid-11453534_1.pdf · 第 2-3 页、第 8 页",
    detail: "该讲比较串行和并行接口。串行/并行主要描述数据位是逐位传输还是多位并行传输，是外设接口形式差异之一。"
  },
  {
    id: "org-34",
    course: "org",
    lecture: "总线",
    topic: "总线概念",
    question: "课件中“总线”的基本定义是什么？",
    options: ["在多于两个模块之间传送信息的公共通路", "只连接一个模块的私有线路", "用于保存程序的磁盘文件", "一种高级编程语言"],
    answer: 0,
    source: "xid-11666310_1.pdf · 第 4 页",
    detail: "总线是在多于两个模块或设备之间传送信息的公共通路，由传输信息的电路和管理信息传输的协议组成。"
  },
  {
    id: "org-35",
    course: "org",
    lecture: "总线",
    topic: "总线分类",
    question: "课件中把 CPU 芯片内部的总线称为什么？",
    options: ["片总线或片上总线", "外总线或通信总线", "互联网骨干网", "磁盘文件系统"],
    answer: 0,
    source: "xid-11666310_1.pdf · 第 5-6 页",
    detail: "课件区分片总线、内总线和外总线。片总线又称器件级总线，对应中央处理器芯片内部的总线。"
  },
  {
    id: "org-36",
    course: "org",
    lecture: "总线",
    topic: "系统总线",
    question: "通常所说微型计算机总线多指哪一类？",
    options: ["内总线，也称系统总线或板级总线", "片内一根门电路连线", "浏览器地址栏", "DNS 根服务器链路"],
    answer: 0,
    source: "xid-11666310_1.pdf · 第 6 页",
    detail: "内总线又称系统总线或板级总线，是计算机系统中各插件板之间信息传输的通路，课件指出通常称为微型计算机总线的即指内总线。"
  },
  {
    id: "org-37",
    course: "org",
    lecture: "总线",
    topic: "AMBA",
    question: "AMBA 的英文全称是什么？",
    options: ["Advanced Microcontroller Bus Architecture", "Automatic Memory Binary Algorithm", "Application Message Bus Address", "Advanced Mail Buffer Adapter"],
    answer: 0,
    source: "xid-11666310_1.pdf · 第 32 页",
    detail: "课件列出 AMBA 总线标准，AMBA 是 Advanced Microcontroller Bus Architecture。"
  },
  {
    id: "org-38",
    course: "org",
    lecture: "总线",
    topic: "Burst",
    question: "Burst 传输在课件中举例用于什么场景？",
    options: ["高速缓存的行填充和行替换", "HTTP Cookie 设置", "键盘按键去抖", "DNSSEC 签名验证"],
    answer: 0,
    source: "xid-11666310_1.pdf · 第 52 页",
    detail: "课件把 Burst 传输应用到 Cache 行填充（读）和行替换（写），连续传输一个数据块能提高效率。"
  },
  {
    id: "org-39",
    course: "org",
    lecture: "先进技术",
    topic: "SoC",
    question: "SoC 指的是什么？",
    options: ["将计算机或其他电子系统集成到单一芯片的集成电路", "只包含一个机械开关的电路", "网络层地址转换协议", "串行外设的一根线"],
    answer: 0,
    source: "xid-11745056_1.pptx · 第 4-5 页；xid-11400182_1.pdf · 第 63 页",
    detail: "SoC 即 System-on-a-Chip，课件说明它把计算机或其他电子系统集成到单一芯片，在移动计算设备中广泛应用。"
  },
  {
    id: "org-40",
    course: "org",
    lecture: "先进技术",
    topic: "AXI",
    question: "AXI 的一个新特性不包括哪一项？",
    options: ["必须所有读写数据共用同一个单向通道", "读写数据通道分离", "支持多个 outstanding 地址", "支持 out-of-order transaction completion"],
    answer: 0,
    source: "xid-11745056_1.pptx · 第 8-10 页",
    detail: "课件列出 AXI 特性：独立读写数据通道、多个未完成地址、乱序事务完成、非对齐数据等；并非强制所有读写共用一个单向通道。"
  },
  {
    id: "org-41",
    course: "org",
    lecture: "先进技术",
    topic: "片上互连",
    question: "课件中为什么说传统片上总线可能难以满足需求？",
    options: ["一个主模块等待从模块返回数据时，可能阻塞无关传输发起", "因为片上总线完全不能传输地址", "因为总线只能连接两个模块", "因为 SoC 不需要任何互连"],
    answer: 0,
    source: "xid-11745056_1.pptx · 第 7 页",
    detail: "课件举例说明主模块 1 等待从模块 2 的读数据时，会造成主模块 2 到从模块 3 等无关传输无法发起，从而暴露传统总线瓶颈。"
  },
  {
    id: "org-42",
    course: "org",
    lecture: "流水线",
    topic: "BTB",
    question: "BTB 在流水线优化中主要服务于什么？",
    options: ["记录和预测转移指令目标地址", "保存用户密码", "进行浮点除法", "为显示器生成像素"],
    answer: 0,
    source: "xid-11396528_1.pdf · 第 6 页、第 37 页",
    detail: "课件在 Pentium 和 BTB 工作机制图中展示 BTB 与指令 Cache、预取缓存器、转移目标地址和历史位相关，用于分支目标预测。"
  },
  {
    id: "org-43",
    course: "org",
    lecture: "中断异常",
    topic: "定时器",
    question: "定时器在系统中的典型作用更接近哪一项？",
    options: ["提供定时/计数能力，支持系统周期性事件处理", "永久保存程序二进制", "作为主存地址总线", "替代所有外部中断"],
    answer: 0,
    source: "xid-11400182_1.pdf · 第 2-3 页",
    detail: "该讲把定时与计数需求、定时器及系统中的中断和定时作为重点内容。定时器通常用于周期性时钟中断和时间相关管理。"
  },
  {
    id: "org-44",
    course: "org",
    lecture: "控制器",
    topic: "程序执行",
    question: "假想计算机程序示例中，STORE M3, R1 的含义是什么？",
    options: ["将 R1 的内容送入 M3 中", "将 M3 的内容装入 R1", "无条件转向 M3", "把 M1 与 M2 直接清零"],
    answer: 0,
    source: "xid-11241478_1.pdf · 第 6-8 页",
    detail: "课件程序示例用 LOAD、ADD、STORE、JMP 四条指令说明机器语言在存储器中的组织；STORE M3,R1 将 R1 内容写入 M3。"
  },
  {
    id: "org-45",
    course: "org",
    lecture: "基本结构",
    topic: "BIOS/芯片组",
    question: "课件把冯·诺依曼结构原理与 PC 实现对应时，CPU 主要对应哪两部分？",
    options: ["运算器 CA 和控制器 CC", "键盘和显示器", "北桥和南桥之外所有外设", "硬盘和网卡"],
    answer: 0,
    source: "xid-10908613_1.pdf · 第 6 页",
    detail: "课件用示意图把 CA、CC、M、I/O 等与 CPU、主存、北桥、南桥、BIOS 等实现结构相对应，CPU 主要承载运算器和控制器功能。"
  },
  {
    id: "org-46",
    course: "org",
    lecture: "输入输出",
    topic: "模型机",
    question: "带有简单输入输出设备的模型机中，8 个小灯泡更接近哪类设备？",
    options: ["输出设备", "主存储器", "地址译码器", "程序计数器"],
    answer: 0,
    source: "xid-11453534_1.pdf · 第 5-7 页",
    detail: "课件用 8 个手动开关和 8 个小灯泡演示简单 I/O：手动开关用于输入，小灯泡用于输出。"
  },
  {
    id: "org-47",
    course: "org",
    lecture: "总线",
    topic: "总线组成",
    question: "总线除了传输信息的电路，还需要什么来管理传输？",
    options: ["协议", "浏览器", "电子邮件地址", "光标图标"],
    answer: 0,
    source: "xid-11666310_1.pdf · 第 4 页",
    detail: "课件定义总线组成包括传输信息的电路，以及管理信息传输的协议。没有协议，就难以协调多个模块共享通路。"
  },
  {
    id: "org-48",
    course: "org",
    lecture: "x86/CISC",
    topic: "IA-64",
    question: "课件中对 Intel IA-64 的说明更接近哪一项？",
    options: ["独立于 x86 的新体系结构，不兼容 IA-32", "8086 的完全兼容简化版", "只能访问 1MB 内存的 16 位模式", "一种链路层访问控制协议"],
    answer: 0,
    source: "xid-10966019_1.pdf · 第 8 页",
    detail: "课件注释说明 Intel 提出的 IA-64 是独立于 x86 的一种新体系结构，不兼容 IA-32；与 AMD64/x86-64 路线不同。"
  },
  {
    id: "org-49",
    course: "org",
    lecture: "MIPS/RISC",
    topic: "MIPS 发展",
    question: "课件中提到 MIPS R4000 的一个重要发展是什么？",
    options: ["扩展到 64 位", "成为第一款 x86 CPU", "取消所有寄存器", "改为只使用微程序控制"],
    answer: 0,
    source: "xid-11112842_1.pdf · 第 6 页",
    detail: "MIPS 指令发展页列出 R2000、R3000、R4000 等，其中 R4000 于 1992 年扩展到 64 位。"
  },
  {
    id: "org-50",
    course: "org",
    lecture: "先进技术",
    topic: "AXI 通道",
    question: "AXI 读写通道分离的直接好处更接近哪一项？",
    options: ["读传输和写传输可以更独立地组织，提高并发能力", "所有传输必须严格退化为单周期", "不能再进行 burst 传输", "CPU 无法访问 DRAM"],
    answer: 0,
    source: "xid-11745056_1.pptx · 第 8-10 页",
    detail: "AXI 支持 separate read and write data channels，并可发起多个 outstanding 地址，有利于提升片上互连的并发与吞吐能力。"
  },
  {
    id: "ics-1",
    course: "ics",
    lecture: "课程概述",
    topic: "课程视角",
    question: "ICS 课程强调从哪个视角理解计算机系统？",
    options: ["程序员视角，理解程序如何在系统中运行", "只从网页设计视角", "只从电路板焊接视角", "只从数学证明视角"],
    answer: 0,
    source: "ICS01-overview-20240909.pdf · 第 3 页",
    detail: "课程起源页说明该课程注重实践、强调对系统的理解，并继承 CS:APP 的程序员视角。"
  },
  {
    id: "ics-2",
    course: "ics",
    lecture: "Bits/Integers",
    topic: "Byte",
    question: "在 ICS 课件中，一个 byte 包含多少个 bit？",
    options: ["8 个 bit", "2 个 bit", "16 个 bit", "64 个 bit"],
    answer: 0,
    source: "ICS02-bits-bytes-ints-20240912.pdf · 第 4 页",
    detail: "课件明确写出 Byte = 8 bits，因此一个字节可表示二进制 00000000 到 11111111。"
  },
  {
    id: "ics-3",
    course: "ics",
    lecture: "Bits/Integers",
    topic: "十六进制",
    question: "一个 byte 的十六进制表示范围是什么？",
    options: ["00 到 FF", "0 到 7", "000 到 999", "A 到 Z"],
    answer: 0,
    source: "ICS02-bits-bytes-ints-20240912.pdf · 第 4 页",
    detail: "8 位二进制对应十进制 0 到 255，也对应十六进制 00 到 FF。"
  },
  {
    id: "ics-4",
    course: "ics",
    lecture: "Bits/Integers",
    topic: "数据表示",
    question: "在典型 x86-64 平台上，课件表中 long 和 pointer 通常占多少字节？",
    options: ["long 8 字节，pointer 8 字节", "long 4 字节，pointer 2 字节", "long 1 字节，pointer 1 字节", "long 16 字节，pointer 4 字节"],
    answer: 0,
    source: "ICS02-bits-bytes-ints-20240912.pdf · 第 5 页",
    detail: "数据表示表中列出 x86-64 下 long 为 8 字节，pointer 为 8 字节，这也是 64 位平台的常见特征。"
  },
  {
    id: "ics-5",
    course: "ics",
    lecture: "Floating Point",
    topic: "二进制小数",
    question: "二进制小数点右侧第一位代表的权值是多少？",
    options: ["1/2", "2", "1/10", "8"],
    answer: 0,
    source: "ICS03-float-20240914.pdf · 第 4-5 页",
    detail: "二进制小数点右侧各位权值依次是 1/2、1/4、1/8 等，对应 2^-1、2^-2、2^-3。"
  },
  {
    id: "ics-6",
    course: "ics",
    lecture: "Floating Point",
    topic: "浮点主题",
    question: "浮点数这一讲主要不包含下面哪项内容？",
    options: ["Unix 文件描述符共享", "IEEE 浮点标准", "舍入", "浮点加法和乘法"],
    answer: 0,
    source: "ICS03-float-20240914.pdf · 第 2 页",
    detail: "浮点讲主要包括二进制小数、IEEE 浮点标准、例子与性质、舍入、加法乘法和 C 中的浮点。Unix I/O 属于后续系统级 I/O。"
  },
  {
    id: "ics-7",
    course: "ics",
    lecture: "Machine Basics",
    topic: "x86 演化",
    question: "ICS 课件中对 Intel x86 处理器演化的一个重要描述是什么？",
    options: ["向后兼容直到 1978 年引入的 8086", "每一代都完全不兼容上一代", "从不增加新特性", "只用于嵌入式传感器"],
    answer: 0,
    source: "ICS04-machine-basics-20240919.pdf · 第 3 页",
    detail: "课件指出 Intel x86 是 evolutionary design，向后兼容直到 8086，并随着时间增加更多特性。"
  },
  {
    id: "ics-8",
    course: "ics",
    lecture: "Machine Basics",
    topic: "8086",
    question: "8086 在课件里被描述为哪类 Intel 处理器？",
    options: ["第一款 16 位 Intel 处理器，是 IBM PC 和 DOS 的基础", "第一款 64 位 Intel 处理器", "第一款 GPU", "第一款无线网卡"],
    answer: 0,
    source: "ICS04-machine-basics-20240919.pdf · 第 4 页",
    detail: "x86 里程碑页写到 8086 于 1978 年推出，是第一款 16 位 Intel 处理器，也是 IBM PC 与 DOS 的基础。"
  },
  {
    id: "ics-9",
    course: "ics",
    lecture: "Machine Control",
    topic: "ISA 状态",
    question: "从汇编/机器代码视角看，程序员可见状态通常不包括哪一项？",
    options: ["网页 CSS 样式表", "寄存器", "程序计数器 PC", "条件码"],
    answer: 0,
    source: "ICS05-machine-control-20240923.pdf · 第 2 页",
    detail: "课件回顾 ISA 视角下的 CPU/内存状态，包括寄存器、PC、条件码、栈和指令等。CSS 与机器级程序状态无关。"
  },
  {
    id: "ics-10",
    course: "ics",
    lecture: "Machine Control",
    topic: "寻址模式",
    question: "x86-64 一般寻址形式 D(Rb,Ri,S) 表示的地址计算是？",
    options: ["Reg[Rb] + S * Reg[Ri] + D", "D - Rb - Ri - S", "只取 Reg[Ri]", "PC + 条件码"],
    answer: 0,
    source: "ICS05-machine-control-20240923.pdf · 第 5 页",
    detail: "课件给出最一般形式 D(Rb,Ri,S)，即基址寄存器、变址寄存器、比例因子和位移共同形成有效地址。"
  },
  {
    id: "ics-11",
    course: "ics",
    lecture: "Procedures",
    topic: "过程机制",
    question: "过程调用机制通常需要完成哪几类工作？",
    options: ["传递控制、传递数据、分配和释放局部存储", "只修改网页颜色", "只进行 DNS 查询", "只发送网络分组"],
    answer: 0,
    source: "ICS06-machine-procedures-20240926.pdf · 第 3-5 页",
    detail: "Procedures 这一讲强调机制包括 passing control、passing data、managing local data，并结合栈结构与调用约定解释。"
  },
  {
    id: "ics-12",
    course: "ics",
    lecture: "Procedures",
    topic: "call/ret",
    question: "call/ret 指令对主要服务于什么？",
    options: ["过程调用和返回时的控制转移", "缓存块替换", "文件重定向", "线程互斥"],
    answer: 0,
    source: "ICS06-machine-procedures-20240926.pdf · 第 2-4 页",
    detail: "课件目标中提到 push/pop 与 call/ret 的基本功能；call 把控制传到过程入口，ret 返回到调用点。"
  },
  {
    id: "ics-13",
    course: "ics",
    lecture: "Machine Data",
    topic: "数组分配",
    question: "声明 T A[L] 时，数组在内存中一般如何分配？",
    options: ["连续分配 L * sizeof(T) 字节", "每个元素必须随机放在不同页", "只分配 1 个字节", "不占用内存"],
    answer: 0,
    source: "ICS07-machine-data-20240930.pdf · 第 3 页",
    detail: "课件给出数组分配基本原则：T A[L] 是长度为 L 的 T 类型数组，连续占用 L * sizeof(T) 字节。"
  },
  {
    id: "ics-14",
    course: "ics",
    lecture: "Machine Data",
    topic: "数组名",
    question: "在数组访问基本原则中，标识符 A 通常可被用作什么？",
    options: ["指向数组第 0 个元素的指针", "CPU 条件码", "系统调用号", "网络端口号"],
    answer: 0,
    source: "ICS07-machine-data-20240930.pdf · 第 4-5 页",
    detail: "课件说明数组标识符 A 可用作指向元素 0 的指针，类型为 T*。"
  },
  {
    id: "ics-15",
    course: "ics",
    lecture: "Advanced Machine",
    topic: "Union",
    question: "C 中 union 的存储分配通常按什么决定大小？",
    options: ["最大成员的大小", "最小成员的大小", "所有成员大小之和再乘 2", "成员名字长度"],
    answer: 0,
    source: "ICS08-machine-advanced-20241010.pdf · 第 3 页",
    detail: "课件写明 Union Allocation: allocate according to largest element，并且同一时刻只能使用一个字段。"
  },
  {
    id: "ics-16",
    course: "ics",
    lecture: "Advanced Machine",
    topic: "字节序",
    question: "字节序问题主要涉及什么？",
    options: ["多字节对象在内存中按什么字节顺序存放", "函数参数个数", "进程 ID 分配", "缓存行大小固定为 1 字节"],
    answer: 0,
    source: "ICS08-machine-advanced-20241010.pdf · 第 5 页",
    detail: "Byte Ordering Revisited 页指出 short/long/quad words 由连续字节组成，关键问题是最高有效字节和最低有效字节的存放顺序。"
  },
  {
    id: "ics-17",
    course: "ics",
    lecture: "ISA/Logic",
    topic: "ISA",
    question: "Instruction Set Architecture 主要定义了什么视图？",
    options: ["汇编语言视角下的处理器状态和指令", "显示器像素排列", "网页排版规则", "外设机械尺寸"],
    answer: 0,
    source: "ICS09-Processor Arch-ISA&Logic-20241014.pdf · 第 2-4 页",
    detail: "ISA 连接应用程序、编译器、操作系统和处理器实现，定义寄存器、内存、指令等汇编/机器代码可见内容。"
  },
  {
    id: "ics-18",
    course: "ics",
    lecture: "ISA/Logic",
    topic: "Y86-64 状态",
    question: "Y86-64 处理器状态中，CC 表示什么？",
    options: ["条件码", "缓存容量", "控制台颜色", "网络连接数"],
    answer: 0,
    source: "ICS09-Processor Arch-ISA&Logic-20241014.pdf · 第 4 页",
    detail: "Y86-64 状态图中列出 RF、PC、CC、Stat、DMEM 等，其中 CC 是 Condition codes。"
  },
  {
    id: "ics-19",
    course: "ics",
    lecture: "SEQ",
    topic: "顺序实现",
    question: "SEQ: Sequential Implementation 的基本特点更接近哪一项？",
    options: ["按顺序完成一条指令的各阶段，再处理下一条", "让所有指令无限并行", "只处理网络报文", "不需要 PC"],
    answer: 0,
    source: "ICS10-Processor Arch-Sequential-20241017.pdf · 第 1-5 页",
    detail: "Sequential Implementation 围绕 Y86-64 指令的顺序执行组织数据通路和控制逻辑，是理解后续流水线实现的基础。"
  },
  {
    id: "ics-20",
    course: "ics",
    lecture: "SEQ",
    topic: "Y86-64 指令",
    question: "Y86-64 指令集中，irmovq V, rB 的含义更接近哪一项？",
    options: ["把立即数 V 放入寄存器 rB", "从内存删除 V", "无条件停止整个操作系统", "创建新线程"],
    answer: 0,
    source: "ICS10-Processor Arch-Sequential-20241017.pdf · 第 2-4 页",
    detail: "Y86-64 指令表列出 irmovq V,rB，属于立即数到寄存器的移动指令。"
  },
  {
    id: "ics-21",
    course: "ics",
    lecture: "PIPE",
    topic: "流水线思想",
    question: "流水线的核心思想是什么？",
    options: ["把处理过程分成多个阶段，让多个对象在不同阶段并行推进", "所有阶段必须由同一个组合逻辑一次完成", "每次只能等待全部对象完成后再开始下一个", "只适用于洗车，不能用于处理器"],
    answer: 0,
    source: "ICS11-Processor Arch-Pipelined-20241021.pdf · 第 2-5 页",
    detail: "课件用洗车例子解释流水线：将流程分成独立阶段，多个对象依次经过阶段，在同一时刻可有多个对象处于不同阶段。"
  },
  {
    id: "ics-22",
    course: "ics",
    lecture: "PIPE",
    topic: "流水线寄存器",
    question: "流水线化组合逻辑通常需要插入什么来分隔阶段？",
    options: ["流水线寄存器", "DNS 服务器", "文件描述符表", "堆分配器"],
    answer: 0,
    source: "ICS11-Processor Arch-Pipelined-20241021.pdf · 第 2 页、第 5 页",
    detail: "创建流水化 Y86-64 处理器需要 rearranging SEQ 并 inserting pipeline registers，用寄存器隔开流水段。"
  },
  {
    id: "ics-23",
    course: "ics",
    lecture: "Memory Hierarchy",
    topic: "总线",
    question: "传统 CPU 与内存连接中，bus 通常携带哪些信号？",
    options: ["地址、数据和控制信号", "只携带颜色信号", "只携带网页链接", "只携带键盘字母"],
    answer: 0,
    source: "ICS12-memory-hierarchy-20241024.pdf · 第 3 页",
    detail: "课件定义 bus 是 carry address, data, and control signals 的并行线集合，常由多个设备共享。"
  },
  {
    id: "ics-24",
    course: "ics",
    lecture: "Memory Hierarchy",
    topic: "读事务",
    question: "内存读事务的第一步通常是什么？",
    options: ["CPU 将地址 A 放到内存总线上", "主存先随机返回数据", "I/O 桥关闭总线", "缓存删除所有行"],
    answer: 0,
    source: "ICS12-memory-hierarchy-20241024.pdf · 第 4-6 页",
    detail: "Memory Read Transaction 图示说明 CPU 首先将地址 A 放到 memory bus，主存读取地址并返回对应字。"
  },
  {
    id: "ics-25",
    course: "ics",
    lecture: "Cache",
    topic: "局部性",
    question: "时间局部性指什么？",
    options: ["最近被引用的对象很可能在不久后再次被引用", "相邻地址永远不会被访问", "程序只能访问一个字节", "CPU 时间一定单调减少"],
    answer: 0,
    source: "ICS13-cache-memories-20241028.pdf · 第 3 页",
    detail: "局部性原则说明程序倾向于使用最近使用过或地址相近的数据和指令；时间局部性关注最近引用对象的再次使用。"
  },
  {
    id: "ics-26",
    course: "ics",
    lecture: "Cache",
    topic: "缓存层次",
    question: "在存储层次中，越靠近 CPU 的缓存通常具有什么特点？",
    options: ["更小、更快、更昂贵", "更大、更慢、更便宜", "只存储硬盘文件名", "完全不保存数据块"],
    answer: 0,
    source: "ICS13-cache-memories-20241028.pdf · 第 4-5 页",
    detail: "课件展示 memory hierarchy：寄存器、L1、L2、L3、主存、磁盘等，越靠近 CPU 越小越快也更贵。"
  },
  {
    id: "ics-27",
    course: "ics",
    lecture: "Optimization",
    topic: "性能现实",
    question: "程序优化课件强调，性能除了渐进复杂度外还受什么影响？",
    options: ["常数因子和代码写法", "文件扩展名颜色", "变量名是否押韵", "显示器分辨率一定决定所有性能"],
    answer: 0,
    source: "ICS14-optimization-20241031.pdf · 第 3 页",
    detail: "Performance Realities 页指出性能不只有渐进复杂度，常数因子也重要，不同代码写法可能有明显差距。"
  },
  {
    id: "ics-28",
    course: "ics",
    lecture: "Optimization",
    topic: "编译器优化",
    question: "优化编译器通常会做哪些工作？",
    options: ["寄存器分配、代码选择与调度、死代码消除等", "自动理解所有业务需求", "替程序员证明所有算法正确", "把 C 程序变成网页"],
    answer: 0,
    source: "ICS14-optimization-20241031.pdf · 第 4 页",
    detail: "课件列出 optimizing compilers 的作用，包括 register allocation、code selection and ordering、dead code elimination 等。"
  },
  {
    id: "ics-29",
    course: "ics",
    lecture: "Linking",
    topic: "链接",
    question: "链接的核心任务是什么？",
    options: ["把目标文件组合成可执行程序", "把浮点数四舍五入", "给线程加锁", "处理 TCP 连接"],
    answer: 0,
    source: "ICS15-linking-20241107.pdf · 第 2 页",
    detail: "Outline of Linking 写明 linking 是 combining object files into programs，并涉及符号解析、重定位和库。"
  },
  {
    id: "ics-30",
    course: "ics",
    lecture: "Linking",
    topic: "GCC 工具链",
    question: "GCC 作为 compiler driver，会调用哪些阶段工具？",
    options: ["预处理器、编译器、汇编器、链接器等", "浏览器、DNS、交换机、路由器", "锁、信号量、条件变量", "显示器、键盘、鼠标"],
    answer: 0,
    source: "ICS15-linking-20241107.pdf · 第 4-5 页",
    detail: "课件以 GCC 为例说明编译工具链，gcc driver 会调用 cpp、cc1、as/gas、ld 等阶段。"
  },
  {
    id: "ics-31",
    course: "ics",
    lecture: "ECF",
    topic: "控制流",
    question: "普通控制流中，CPU 从启动到关闭主要做什么？",
    options: ["一次一条地读取并执行指令序列", "随机删除内存页", "只等待网络连接", "只显示图片"],
    answer: 0,
    source: "ICS16-ECF1-20241111.pdf · 第 5 页",
    detail: "Control Flow 页指出 CPU 从启动到关闭本质上读取并解释执行一条条指令序列。"
  },
  {
    id: "ics-32",
    course: "ics",
    lecture: "ECF",
    topic: "异常控制流",
    question: "异常控制流 ECF 的意义是什么？",
    options: ["处理非标准控制流，如异常、进程切换、信号等", "只负责浮点加法", "只负责图形渲染", "只负责十六进制打印"],
    answer: 0,
    source: "ICS16-ECF1-20241111.pdf · 第 4 页；ICS17-ECF2-20241114.pdf · 第 2-3 页",
    detail: "ECF 涵盖 exceptions、processes、signals、nonlocal jumps 等，是系统在不同层次处理非线性控制流的核心机制。"
  },
  {
    id: "ics-33",
    course: "ics",
    lecture: "Signals",
    topic: "fork",
    question: "程序员模型中，fork 的一个典型特征是什么？",
    options: ["调用一次，返回两次", "调用一次，永不返回", "只能由浏览器调用", "只改变浮点舍入模式"],
    answer: 0,
    source: "ICS17-ECF2-20241114.pdf · 第 4 页",
    detail: "课件列出 multitasking 基本函数：fork spawns new process，called once, returns twice；exit 则 called once, never returns。"
  },
  {
    id: "ics-34",
    course: "ics",
    lecture: "Signals",
    topic: "信号处理",
    question: "课件中为什么不建议在 signal handler 中使用 printf？",
    options: ["可能重入 printf/puts 导致死锁等问题", "printf 只能打印二进制", "printf 会自动 fork", "printf 会禁用虚拟内存"],
    answer: 0,
    source: "ICS24-CONC-20241212.pdf · 第 5 页",
    detail: "并发讲中的死锁例子指出 signal handler 里调用 printf 可能重入 printf/puts，造成 BAD/DEADLOCK。"
  },
  {
    id: "ics-35",
    course: "ics",
    lecture: "System I/O",
    topic: "Unix I/O",
    question: "Unix I/O 的一个核心抽象是什么？",
    options: ["Linux 文件是字节序列，I/O 设备也表示为文件", "所有 I/O 都必须用浮点数表示", "文件只能读不能写", "打开文件不需要内核参与"],
    answer: 0,
    source: "ICS18-SysIO-20241118.pdf · 第 4-5 页",
    detail: "课件说明 Linux file 是 m 字节序列，并指出所有 I/O 设备都表示为文件，内核导出 open/close/read/write 等简单接口。"
  },
  {
    id: "ics-36",
    course: "ics",
    lecture: "System I/O",
    topic: "RIO",
    question: "RIO package 的目的更接近哪一项？",
    options: ["封装健壮 I/O，处理错误检查、信号和 short counts 等", "把程序链接成可执行文件", "进行浮点数舍入", "为缓存选择组索引"],
    answer: 0,
    source: "ICS18-SysIO-20241118.pdf · 第 2-3 页",
    detail: "课件提到 Robust I/O 是 15-213 special wrappers，是良好编码实践，可处理错误检查、信号和 short counts。"
  },
  {
    id: "ics-37",
    course: "ics",
    lecture: "Virtual Memory",
    topic: "虚拟内存用途",
    question: "虚拟内存在 ICS 课件中不被用作哪一项？",
    options: ["HTTP 状态码分类", "缓存工具", "内存管理工具", "内存保护工具"],
    answer: 0,
    source: "ICS19-VM1-20241125.pdf · 第 3 页",
    detail: "VM 概念讲列出虚拟内存作为 caching、memory management、memory protection 的工具，并介绍地址翻译。"
  },
  {
    id: "ics-38",
    course: "ics",
    lecture: "Virtual Memory",
    topic: "进程地址空间",
    question: "从程序员视角看，虚拟内存给每个进程提供什么？",
    options: ["私有的线性地址空间", "全局共享同一栈指针", "固定唯一的物理页号", "只能访问内核代码"],
    answer: 0,
    source: "ICS20-VM2-20241128.pdf · 第 3 页",
    detail: "VM 系统讲复习指出，每个进程拥有自己的 private linear address space，不能被其他进程破坏。"
  },
  {
    id: "ics-39",
    course: "ics",
    lecture: "Virtual Memory",
    topic: "地址翻译",
    question: "地址翻译中，虚拟地址通常被分成哪两部分？",
    options: ["虚拟页号 VPN 和虚拟页偏移 VPO", "文件名和扩展名", "端口号和 IP 地址", "条件码和状态码"],
    answer: 0,
    source: "ICS20-VM2-20241128.pdf · 第 5 页",
    detail: "Address Translation 图中虚拟地址被划分为 Virtual page number 和 Virtual page offset，并通过页表进行转换。"
  },
  {
    id: "ics-40",
    course: "ics",
    lecture: "Dynamic Memory",
    topic: "堆",
    question: "动态内存分配器主要管理哪一块运行时区域？",
    options: ["Heap", "CPU 条件码寄存器", "指令译码器", "以太网交换机表"],
    answer: 0,
    source: "ICS21-DMM-20241202.pdf · 第 3-4 页",
    detail: "课件图中动态内存分配器位于运行时创建的 heap 上，维护已分配和空闲的可变大小块。"
  },
  {
    id: "ics-41",
    course: "ics",
    lecture: "Dynamic Memory",
    topic: "malloc",
    question: "malloc(size) 成功时返回什么？",
    options: ["指向至少 size 字节内存块的指针", "新进程的 PID", "文件描述符 0", "CPU 缓存命中率"],
    answer: 0,
    source: "ICS21-DMM-20241202.pdf · 第 5 页",
    detail: "malloc package 页说明 malloc 成功时返回指向至少 size 字节内存块的指针，并按平台要求对齐。"
  },
  {
    id: "ics-42",
    course: "ics",
    lecture: "Network Programming",
    topic: "协议",
    question: "网络协议主要做什么？",
    options: ["定义主机地址格式、路由交付等通信规则", "决定 C 语言数组长度", "管理堆空闲链表", "替代所有系统调用"],
    answer: 0,
    source: "ICS23-netprog-20241209.pdf · 第 2-3 页",
    detail: "Network Programming 讲说明 internet protocol 提供 naming scheme，并定义 host address 的统一格式及交付机制。"
  },
  {
    id: "ics-43",
    course: "ics",
    lecture: "Network Programming",
    topic: "Client-Server",
    question: "客户端-服务器模型中，服务器进程通常做什么？",
    options: ["管理某种资源，并响应客户端请求", "只显示本地图片", "只执行浮点舍入", "只释放堆块"],
    answer: 0,
    source: "ICS23-netprog-20241209.pdf · 第 4 页",
    detail: "课件描述网络应用常基于 client-server model：服务器进程管理资源，客户端进程向服务器请求服务。"
  },
  {
    id: "ics-44",
    course: "ics",
    lecture: "Concurrent",
    topic: "并发难点",
    question: "并发编程难的一个原因是什么？",
    options: ["需要考虑事件的所有可能交错顺序", "所有程序都只能顺序执行", "CPU 不能执行指令", "文件不能被多个进程打开"],
    answer: 0,
    source: "ICS24-CONC-20241212.pdf · 第 2 页",
    detail: "课件指出人脑倾向于顺序思维，时间概念容易误导，而并发系统中事件顺序组合很多。"
  },
  {
    id: "ics-45",
    course: "ics",
    lecture: "Concurrent",
    topic: "数据竞争",
    question: "Data race 通常出现在什么场景？",
    options: ["多个并发执行流未正确同步地访问共享数据", "单线程只读常量", "程序只执行一次 return", "没有任何共享状态"],
    answer: 0,
    source: "ICS24-CONC-20241212.pdf · 第 3 页；ICS25-SYNC1-20241216.pdf · 第 2-5 页",
    detail: "并发和同步课件连续讨论 data race、sharing、mutual exclusion。多个线程共享数据且缺少同步时容易产生数据竞争。"
  },
  {
    id: "ics-46",
    course: "ics",
    lecture: "Synchronization",
    topic: "线程",
    question: "一个进程内的多个线程通常共享什么？",
    options: ["同一进程的代码、数据和内核上下文", "各自完全独立的地址空间", "不同机器上的物理内存", "不同的可执行文件格式"],
    answer: 0,
    source: "ICS25-SYNC1-20241216.pdf · 第 4-5 页",
    detail: "课件说明多个线程可关联到同一进程，每个线程有自己的逻辑控制流，但共享同一代码、数据和内核上下文。"
  },
  {
    id: "ics-47",
    course: "ics",
    lecture: "Synchronization",
    topic: "互斥",
    question: "互斥的目标是什么？",
    options: ["保护共享资源，避免多个线程同时进入临界区", "让所有线程永久阻塞", "关闭所有缓存", "禁止函数调用"],
    answer: 0,
    source: "ICS25-SYNC1-20241216.pdf · 第 2 页；ICS26-SYNC2-20241219.pdf · 第 3-4 页",
    detail: "同步课件讨论 sharing、mutual exclusion、semaphores。互斥通过锁或信号量保护共享变量或资源。"
  },
  {
    id: "ics-48",
    course: "ics",
    lecture: "Synchronization",
    topic: "Semaphore",
    question: "信号量在课件中被描述为什么？",
    options: ["非负全局整数同步变量，由 P/V 操作操纵", "浮点舍入模式", "机器指令编码前缀", "网页缓存条目"],
    answer: 0,
    source: "ICS26-SYNC2-20241219.pdf · 第 2 页",
    detail: "Semaphore 是 non-negative global integer synchronization variable，通过 P 和 V 操作进行同步。"
  },
  {
    id: "ics-49",
    course: "ics",
    lecture: "Synchronization",
    topic: "生产者-消费者",
    question: "生产者-消费者问题中，生产者通常等待什么？",
    options: ["缓冲区有空槽后插入项目", "所有消费者退出系统", "虚拟地址翻译关闭", "链接器完成符号解析"],
    answer: 0,
    source: "ICS26-SYNC2-20241219.pdf · 第 5 页",
    detail: "课件描述 producer waits for empty slot, inserts item in buffer, and notifies consumer，是常见同步模式。"
  },
  {
    id: "ics-50",
    course: "ics",
    lecture: "Future Computing",
    topic: "摩尔定律",
    question: "摩尔定律最初关注的核心趋势是什么？",
    options: ["芯片上最优器件数量随时间快速增加", "网络带宽永远不变", "程序行数每年减半", "所有计算机都只能单核"],
    answer: 0,
    source: "ICS27-future computing-20241223.pdf · 第 2-4 页",
    detail: "课件介绍 Moore’s Law 起源：每个芯片上的最优器件数量持续增长，后续常概括为约每两年翻倍。"
  },
  {
    id: "ics-51",
    course: "ics",
    lecture: "Future Computing",
    topic: "计算发展",
    question: "课件用 Cray 1 与现代手机芯片对比，主要想说明什么？",
    options: ["几十年来单芯片复杂度和处理能力显著提高", "手机不能进行任何计算", "超级计算机没有晶体管", "摩尔定律只影响机械硬盘"],
    answer: 0,
    source: "ICS27-future computing-20241223.pdf · 第 5 页",
    detail: "What Moore’s Law Has Meant 页通过 Cray 1 与现代手机 SoC 对比，展示晶体管数量和运算能力的巨大提升。"
  },
  {
    id: "ics-52",
    course: "ics",
    lecture: "Cache",
    topic: "缓存块",
    question: "缓存通常以什么为单位在相邻层次间复制数据？",
    options: ["块/缓存行大小的传输单元", "单个 C 变量名", "整个进程地址空间", "所有磁盘文件一次性复制"],
    answer: 0,
    source: "ICS13-cache-memories-20241028.pdf · 第 5 页",
    detail: "General Cache Concepts 页说明较小较快的缓存保存较大较慢存储中的块子集，数据按 block-sized transfer units 复制。"
  },
  {
    id: "compiler-1",
    course: "compiler",
    lecture: "词法分析",
    topic: "状态转换图",
    question: "状态转换图中的接受状态通常表示什么？",
    options: ["已经识别出一个词素", "发生语法规约", "完成寄存器分配", "进入垃圾回收阶段"],
    answer: 0,
    source: "Arthals《词法分析 II》https://arthals.ink/blog/lexical-2",
    detail: "状态表示识别词素时的当前情况，接受状态或最终状态表示已经找到了一个词素。"
  },
  {
    id: "compiler-2",
    course: "compiler",
    lecture: "词法分析",
    topic: "最长匹配",
    question: "词法分析匹配过程中，当多个前缀都能匹配时通常选择什么？",
    options: ["最长匹配", "最短匹配", "随机匹配", "最后一个字符单独成词"],
    answer: 0,
    source: "Arthals《词法分析 II》https://arthals.ink/blog/lexical-2",
    detail: "笔记在“匹配过程中需要解决的问题”中说明，需要确定匹配长度，多个前缀可匹配时选择最长匹配。"
  },
  {
    id: "compiler-3",
    course: "compiler",
    lecture: "词法分析",
    topic: "规则优先级",
    question: "当多个正则表达式都能匹配同一最长前缀时，Lex 类工具通常如何选择？",
    options: ["优先匹配写在前面的规则", "优先匹配写在最后的规则", "总是报错", "把所有规则结果拼接"],
    answer: 0,
    source: "Arthals《词法分析 II》https://arthals.ink/blog/lexical-2",
    detail: "笔记指出若多个正则表达式匹配，应优先匹配前面的规则；ERROR 规则通常放在表末尾用于报错。"
  },
  {
    id: "compiler-4",
    course: "compiler",
    lecture: "词法分析",
    topic: "Lex",
    question: "Lex 的主要作用是什么？",
    options: ["根据正则表达式自动生成词法分析程序", "执行 LR(1) 语法规约", "完成目标代码寄存器着色", "管理运行时堆空间"],
    answer: 0,
    source: "Arthals《词法分析 II》https://arthals.ink/blog/lexical-2",
    detail: "Lex 是词法分析程序自动构造工具，利用正则表达式与自动机的等价性生成词法分析器。"
  },
  {
    id: "compiler-5",
    course: "compiler",
    lecture: "词法分析",
    topic: "自动机构造",
    question: "从正则表达式构造词法分析器时，常见转换路径是？",
    options: ["正则表达式 -> NFA -> DFA -> 最小 DFA", "CFG -> LR(1) -> 汇编 -> 堆", "AST -> 寄存器 -> Token -> NFA", "DFA -> 源程序 -> 正则表达式 -> 语法树"],
    answer: 0,
    source: "Arthals《词法分析 II》https://arthals.ink/blog/lexical-2",
    detail: "笔记给出的实现原理是正则表达式到 NFA，再到 DFA，最后可进行 DFA 最小化。"
  },
  {
    id: "compiler-6",
    course: "compiler",
    lecture: "词法分析",
    topic: "ε-closure",
    question: "ε_closure(S) 指的是什么？",
    options: ["从 S 中任一状态出发，仅沿 ε 弧可到达的状态集合，包括 S 自身", "所有非终结符的 Follow 集", "所有寄存器冲突边集合", "所有基本块后继集合"],
    answer: 0,
    source: "Arthals《词法分析 III》https://arthals.ink/blog/lexical-3",
    detail: "ε 闭包用于 NFA 到 DFA 的子集构造，是从状态集合出发通过空转换可达的所有状态。"
  },
  {
    id: "compiler-7",
    course: "compiler",
    lecture: "词法分析",
    topic: "NFA 到 DFA",
    question: "子集构造法得到的 DFA 中，一个 DFA 状态对应什么？",
    options: ["原 NFA 的一个状态集合", "原 NFA 的单条边", "一个语法产生式左部", "一个物理寄存器"],
    answer: 0,
    source: "Arthals《词法分析 III》https://arthals.ink/blog/lexical-3",
    detail: "笔记说明 DFA M' 中的每个状态都是 NFA M 的状态集合，初始状态为 ε_closure({t0})。"
  },
  {
    id: "compiler-8",
    course: "compiler",
    lecture: "词法分析",
    topic: "DFA 最小化",
    question: "DFA 最小化的目标是什么？",
    options: ["找到状态数更少且接受同一语言的 DFA", "让 DFA 接受所有字符串", "把所有终态删除", "把 DFA 转回源代码"],
    answer: 0,
    source: "Arthals《词法分析 III》https://arthals.ink/blog/lexical-3",
    detail: "DFA 最小化寻找状态数更少的 DFA M'，使得 L(M') = L(M)。"
  },
  {
    id: "compiler-9",
    course: "compiler",
    lecture: "语法分析",
    topic: "CFG",
    question: "程序设计语言的语法通常可用什么描述？",
    options: ["上下文无关文法或 BNF 表示法", "只用寄存器冲突图", "只用垃圾回收器", "只用物理地址表"],
    answer: 0,
    source: "Arthals《语法分析 I》https://arthals.ink/blog/syntax-1",
    detail: "笔记在语法分析概述中说明，程序设计语言构造的语法可用上下文无关文法或 BNF 表示。"
  },
  {
    id: "compiler-10",
    course: "compiler",
    lecture: "语法分析",
    topic: "语法分析器",
    question: "语法分析器的基本功能是什么？",
    options: ["根据文法规则识别语法成分并进行语法检查", "把目标代码装入寄存器", "把堆对象标记清扫", "判断缓存是否命中"],
    answer: 0,
    source: "Arthals《语法分析 I》https://arthals.ink/blog/syntax-1",
    detail: "语法分析器从词法分析器提供的 Token 串中识别语法成分，检查是否符合文法。"
  },
  {
    id: "compiler-11",
    course: "compiler",
    lecture: "语法分析",
    topic: "文法层次",
    question: "乔姆斯基层次中，2 型文法通常指什么？",
    options: ["上下文无关文法 CFG", "正则文法", "任意文法", "上下文有关文法"],
    answer: 0,
    source: "Arthals《语法分析 I》https://arthals.ink/blog/syntax-1",
    detail: "笔记列出 0 型任意文法、1 型上下文有关、2 型上下文无关、3 型正则文法。"
  },
  {
    id: "compiler-12",
    course: "compiler",
    lecture: "语法分析",
    topic: "二义性",
    question: "dangling-else 问题的二义性来自哪里？",
    options: ["else 可以和多个未匹配的 then/if 关联", "词法分析不能识别数字", "寄存器数量不足", "DFA 没有初始状态"],
    answer: 0,
    source: "Arthals《语法分析 II》https://arthals.ink/blog/syntax-2",
    detail: "笔记说明 dangling-else 中同一个 else 可能匹配外层或内层 if，需通过改写文法消除二义性。"
  },
  {
    id: "compiler-13",
    course: "compiler",
    lecture: "语法分析",
    topic: "左递归",
    question: "为什么自顶向下分析通常要消除左递归？",
    options: ["左递归可能导致递归下降分析无限递归", "左递归会让词法分析器无法读字符", "左递归必然导致寄存器溢出", "左递归会删除所有终结符"],
    answer: 0,
    source: "Arthals《语法分析 II》https://arthals.ink/blog/syntax-2",
    detail: "自顶向下分析从根部展开，直接或间接左递归会使递归下降不断调用自身，因此需要改写。"
  },
  {
    id: "compiler-14",
    course: "compiler",
    lecture: "语法分析",
    topic: "LL(1)",
    question: "LL(1) 分析依赖的两个重要集合是？",
    options: ["First 集和 Follow 集", "Use 集和 Def 集", "In 集和 Out 集的寄存器图", "Heap 集和 Stack 集"],
    answer: 0,
    source: "Arthals《语法分析 II》https://arthals.ink/blog/syntax-2",
    detail: "预测分析表的构造需要 First 和 Follow 集，用于选择合适产生式并处理 ε 推导。"
  },
  {
    id: "compiler-15",
    course: "compiler",
    lecture: "语法分析",
    topic: "自底向上",
    question: "自底向上语法分析的过程可以理解为？",
    options: ["把输入串逐步归约回文法开始符号", "从开始符号只做最左推导", "只做词法最长匹配", "只做死代码删除"],
    answer: 0,
    source: "Arthals《语法分析 III》https://arthals.ink/blog/syntax-3",
    detail: "自底向上分析在每个 reduction 步骤中，把与产生式右部匹配的子串替换为产生式左部非终结符。"
  },
  {
    id: "compiler-16",
    course: "compiler",
    lecture: "语法分析",
    topic: "句柄",
    question: "句柄 handle 是什么？",
    options: ["可按某产生式规约、对应最右推导反向一步的子串", "DFA 的唯一初始状态", "目标机的一条 load 指令", "堆中的空闲块头"],
    answer: 0,
    source: "Arthals《语法分析 III》https://arthals.ink/blog/syntax-3",
    detail: "笔记把句柄定义为与某个产生式体匹配的子串，对它规约代表最右推导中的一个反向步骤。"
  },
  {
    id: "compiler-17",
    course: "compiler",
    lecture: "语法分析",
    topic: "LR(0)",
    question: "LR(0) 项集规范族通常通过哪些过程构造？",
    options: ["Closure 和 Goto", "malloc 和 free", "load 和 store", "mark 和 sweep"],
    answer: 0,
    source: "Arthals《语法分析 III》https://arthals.ink/blog/syntax-3",
    detail: "LR(0) 自动机和项集规范族构造依赖项集闭包 Closure 与 Goto 函数。"
  },
  {
    id: "compiler-18",
    course: "compiler",
    lecture: "语法分析",
    topic: "LR(1)",
    question: "LR(1) 项相比 LR(0) 项多了什么信息？",
    options: ["向前搜索符号/展望符号", "物理寄存器编号", "堆对象颜色", "目标机字长"],
    answer: 0,
    source: "Arthals《语法分析 IV》https://arthals.ink/blog/syntax-4",
    detail: "LR(k) 项形式为 [A -> α·β, a1...ak]，其中 a1...ak 是向前搜索符号串；LR(1) 使用一个展望符号。"
  },
  {
    id: "compiler-19",
    course: "compiler",
    lecture: "语法分析",
    topic: "LR 冲突",
    question: "利用优先级和结合性常用于解决哪类问题？",
    options: ["某些 LR 分析表冲突", "DFA 初始状态不存在", "活动记录没有返回地址", "目标机没有内存"],
    answer: 0,
    source: "Arthals《语法分析 IV》https://arthals.ink/blog/syntax-4",
    detail: "笔记在 LR(1)/LALR 讨论中列出可利用优先级和结合性消除冲突。"
  },
  {
    id: "compiler-20",
    course: "compiler",
    lecture: "语法制导翻译",
    topic: "SDD",
    question: "语法制导定义 SDD 是什么？",
    options: ["上下文无关文法与属性/语义规则的结合", "一个 DFA 的最小化算法", "寄存器着色结果", "运行时垃圾回收器"],
    answer: 0,
    source: "Arthals《语法制导翻译 I》https://arthals.ink/blog/sdt-1",
    detail: "SDD 将文法符号和属性相关联，并用语义规则描述属性值如何计算。"
  },
  {
    id: "compiler-21",
    course: "compiler",
    lecture: "语法制导翻译",
    topic: "综合属性",
    question: "综合属性通常沿语法树的哪个方向传播？",
    options: ["自下而上", "只能自上而下", "只在兄弟节点之间循环", "完全不传播"],
    answer: 0,
    source: "Arthals《语法制导翻译 I》https://arthals.ink/blog/sdt-1",
    detail: "综合属性一般由子节点属性等计算得到，向父节点汇总，因此常自下而上传递。"
  },
  {
    id: "compiler-22",
    course: "compiler",
    lecture: "语法制导翻译",
    topic: "继承属性",
    question: "继承属性通常可以依赖哪些信息？",
    options: ["父节点、自己或兄弟节点的属性", "只能依赖子节点综合属性", "只能依赖目标机寄存器", "只能依赖垃圾回收结果"],
    answer: 0,
    source: "Arthals《语法制导翻译 I》https://arthals.ink/blog/sdt-1",
    detail: "笔记说明继承属性是某个符号的属性，可由父节点、自身或兄弟节点相关属性计算。"
  },
  {
    id: "compiler-23",
    course: "compiler",
    lecture: "语法制导翻译",
    topic: "SDT",
    question: "语法制导翻译 SDT 相比 SDD 的特点是？",
    options: ["在产生式体中加入语义动作并在适当时机执行", "只定义正则表达式", "只构造 DFA 状态集合", "只进行寄存器溢出"],
    answer: 0,
    source: "Arthals《语法制导翻译 I》https://arthals.ink/blog/sdt-1",
    detail: "SDT 在产生式体中嵌入语义动作，分析过程中执行这些动作来完成语义检查或翻译。"
  },
  {
    id: "compiler-24",
    course: "compiler",
    lecture: "语法制导翻译",
    topic: "AST",
    question: "抽象语法树 AST 相比具体语法树通常会省略什么？",
    options: ["标点符号等非本质信息", "所有运算符", "所有语义信息", "所有子节点"],
    answer: 0,
    source: "Arthals《语法制导翻译 II》https://arthals.ink/blog/sdt-2",
    detail: "AST 每个结点代表语法结构，子结点代表组成部分；它可忽略标点等非本质内容。"
  },
  {
    id: "compiler-25",
    course: "compiler",
    lecture: "语法制导翻译",
    topic: "while 翻译",
    question: "翻译 while 语句时，循环体结束后通常应跳转到哪里？",
    options: ["循环条件判断处", "程序入口之前", "任意终结符", "寄存器冲突图"],
    answer: 0,
    source: "Arthals《语法制导翻译 III》https://arthals.ink/blog/sdt-3",
    detail: "while 循环体结束后需要跳回条件表达式处，继续下一轮条件判断。"
  },
  {
    id: "compiler-26",
    course: "compiler",
    lecture: "语法制导翻译",
    topic: "布尔控制流",
    question: "控制流翻译中 C.true 和 C.false 属性通常表示什么？",
    options: ["条件为真/假时要跳转到的代码标号", "两个物理寄存器", "两个 DFA 终态", "两个堆块大小"],
    answer: 0,
    source: "Arthals《语法制导翻译 III》https://arthals.ink/blog/sdt-3",
    detail: "笔记说明 C.true 是条件为真时执行代码的开始标号，C.false 是条件为假时执行代码的开始标号。"
  },
  {
    id: "compiler-27",
    course: "compiler",
    lecture: "中间代码",
    topic: "IR",
    question: "中间代码的主要特点是什么？",
    options: ["介于源代码和目标代码之间，尽量不依赖具体语言和目标机", "只能是某一种 CPU 的机器码", "只能由垃圾回收器生成", "只用于词法分析错误恢复"],
    answer: 0,
    source: "Arthals《中间代码生成 I》https://arthals.ink/blog/ir-generation-1",
    detail: "中间代码不依赖具体源语言和目标机，方便多语言复用、生成多目标机器码，并进行机器无关优化。"
  },
  {
    id: "compiler-28",
    course: "compiler",
    lecture: "中间代码",
    topic: "DAG",
    question: "DAG 相比 AST 的一个重要区别是？",
    options: ["尽可能复用相同节点以共享公共子表达式", "必须保留所有标点符号", "不能表示表达式", "只能表示正则语言"],
    answer: 0,
    source: "Arthals《中间代码生成 I》https://arthals.ink/blog/ir-generation-1",
    detail: "笔记说明 DAG 与 AST 的区别是尽可能复用相同节点，可能降低生成效率但提高运行效率。"
  },
  {
    id: "compiler-29",
    course: "compiler",
    lecture: "中间代码",
    topic: "三地址代码",
    question: "三地址代码属于哪类表示？",
    options: ["中间代码表示形式", "正则表达式最小化算法", "运行时存储分配策略", "目标机物理寄存器集合"],
    answer: 0,
    source: "Arthals《中间代码生成 I》https://arthals.ink/blog/ir-generation-1",
    detail: "笔记列出 AST、DAG、后缀式和三地址代码等中间代码表示形式。"
  },
  {
    id: "compiler-30",
    course: "compiler",
    lecture: "中间代码",
    topic: "临时变量",
    question: "表达式代码生成 SDD 中 newTemp() 通常用于什么？",
    options: ["生成新的临时变量", "生成新的 DFA 终态", "分配新的物理寄存器颜色", "清空堆空间"],
    answer: 0,
    source: "Arthals《中间代码生成 II》https://arthals.ink/blog/ir-generation-2",
    detail: "笔记在生成表达式代码的 SDD 中说明 newTemp() 可以生成一个临时变量，addr 保存表达式结果地址。"
  },
  {
    id: "compiler-31",
    course: "compiler",
    lecture: "中间代码",
    topic: "数组寻址",
    question: "一维数组 A[i] 地址计算通常依赖哪些信息？",
    options: ["数组起始地址 base、元素宽度 w、下标 i", "DFA 接受状态和 LR 项", "寄存器冲突边和颜色", "垃圾回收标记位和扫描栈"],
    answer: 0,
    source: "Arthals《中间代码生成 II》https://arthals.ink/blog/ir-generation-2",
    detail: "一维数组元素连续存放，地址计算依赖 A[0] 起始地址 base、每个元素宽度 w 和元素编号。"
  },
  {
    id: "compiler-32",
    course: "compiler",
    lecture: "中间代码",
    topic: "回填",
    question: "回填技术主要用于什么场景？",
    options: ["先生成跳转指令，待目标标号确定后再补上地址", "将 DFA 状态压缩为一个状态", "把所有变量放入同一寄存器", "提前释放所有堆对象"],
    answer: 0,
    source: "Arthals《中间代码生成 II》https://arthals.ink/blog/ir-generation-2",
    detail: "布尔表达式和控制流翻译中，跳转目标常在生成时未知，因此使用回填技术延迟填写目标。"
  },
  {
    id: "compiler-33",
    course: "compiler",
    lecture: "Koopa",
    topic: "基本块",
    question: "在 Koopa IR 笔记中，基本块如何直观识别？",
    options: ["由标号分开的代码区域", "每一个字符都是一个基本块", "每个变量声明都是一个函数", "每个 DFA 状态都是基本块"],
    answer: 0,
    source: "Arthals《Koopa IR 人话版》https://arthals.ink/blog/koopa",
    detail: "笔记通过 if 示例说明，每个标号分开的区域就是一个基本块。"
  },
  {
    id: "compiler-34",
    course: "compiler",
    lecture: "Koopa",
    topic: "Value",
    question: "Koopa IR 中很多指令可以被看作什么？",
    options: ["一个 value，引用其他 value 并产生结果或副作用", "一个正则表达式字符类", "一个 LR(0) 项集", "一个垃圾回收根集合"],
    answer: 0,
    source: "Arthals《Koopa IR 人话版》https://arthals.ink/blog/koopa",
    detail: "笔记指出大多数指令就是一个值，它们引用一些别的值并完成相应操作。"
  },
  {
    id: "compiler-35",
    course: "compiler",
    lecture: "Koopa",
    topic: "基本块结尾",
    question: "Koopa IR 测试点笔记中强调，基本块结尾必须是什么之一？",
    options: ["br、jump 或 ret", "load、alloc 或 add", "DFA、NFA 或 CFG", "malloc、free 或 mark"],
    answer: 0,
    source: "Arthals《编译原理大作业的奇妙测试点们》https://arthals.ink/blog/compile-principle-testcases",
    detail: "笔记提醒基本块结尾必须是 br、jump 或 ret，并且这些指令只能出现在基本块结尾。"
  },
  {
    id: "compiler-36",
    course: "compiler",
    lecture: "运行时",
    topic: "运行时环境",
    question: "运行时环境的主要作用是什么？",
    options: ["实现存储组织和过程抽象", "只进行词法最长匹配", "只最小化 DFA", "只生成 First 集"],
    answer: 0,
    source: "Arthals《运行时环境》https://arthals.ink/blog/runtime",
    detail: "笔记开头说明运行时环境主要作用是实现存储组织和过程抽象，并受源语言特性影响。"
  },
  {
    id: "compiler-37",
    course: "compiler",
    lecture: "运行时",
    topic: "活动记录",
    question: "活动记录 activation record 通常服务于什么？",
    options: ["过程调用时保存局部数据、返回信息和控制/访问链等运行时信息", "DFA 状态等价划分", "正则表达式优先级排序", "目标机寻址模式选择"],
    answer: 0,
    source: "Arthals《运行时环境》https://arthals.ink/blog/runtime",
    detail: "运行时环境笔记围绕活动记录、访问链、控制链和活动记录指针讲解过程调用时的栈式管理。"
  },
  {
    id: "compiler-38",
    course: "compiler",
    lecture: "运行时",
    topic: "垃圾回收",
    question: "引用计数垃圾回收的基本思想是？",
    options: ["记录对象被引用次数，次数降为 0 时可回收", "把所有对象复制到寄存器", "只保留最后一个 Token", "把所有 LR 项合并"],
    answer: 0,
    source: "Arthals《运行时环境》https://arthals.ink/blog/runtime",
    detail: "运行时环境笔记讨论引用计数、标记-清扫、标记-压缩、拷贝回收器和世代回收器等垃圾回收方案。"
  },
  {
    id: "compiler-39",
    course: "compiler",
    lecture: "目标代码",
    topic: "目标机模型",
    question: "目标代码生成笔记中的目标机模型更接近哪类机器？",
    options: ["类 RISC、按字节寻址、4 字节为一个 word", "纯栈机且不能使用寄存器", "只能识别正则表达式", "没有内存和分支指令"],
    answer: 0,
    source: "Arthals《目标代码生成》https://arthals.ink/blog/code-generation",
    detail: "笔记设定目标机为类 RISC 计算机，按字节寻址，4 字节为 1 个字，并有通用寄存器和常见机器指令。"
  },
  {
    id: "compiler-40",
    course: "compiler",
    lecture: "目标代码",
    topic: "load/store",
    question: "目标机指令 ST x, r 的含义是什么？",
    options: ["把寄存器 r 中的值保存到位置 x", "把位置 x 加载到寄存器 r", "无条件跳转到 x", "声明一个终结符"],
    answer: 0,
    source: "Arthals《目标代码生成》https://arthals.ink/blog/code-generation",
    detail: "目标机模型中 LD 负责加载，ST x,r 表示 store，把寄存器 r 的值保存到位置 x。"
  },
  {
    id: "compiler-41",
    course: "compiler",
    lecture: "目标代码",
    topic: "基本块",
    question: "划分基本块通常以什么为单位分析控制流？",
    options: ["顺序执行、只有入口和出口的指令序列", "单个字符", "一个正则表达式", "一个堆对象"],
    answer: 0,
    source: "Arthals《目标代码生成》https://arthals.ink/blog/code-generation",
    detail: "目标代码生成笔记讨论控制流图、三地址代码和基本块划分。基本块是控制流分析和局部优化的基础单位。"
  },
  {
    id: "compiler-42",
    course: "compiler",
    lecture: "目标代码",
    topic: "活跃变量",
    question: "活跃变量分析主要用于判断什么？",
    options: ["某变量的值在程序某点之后是否还可能被使用", "某状态是否为 DFA 初态", "某文法是否有终结符", "某对象是否一定在堆上"],
    answer: 0,
    source: "Arthals《目标代码生成》https://arthals.ink/blog/code-generation",
    detail: "活跃变量分析是目标代码生成和寄存器分配的重要数据流分析，用于判断值是否仍需保留。"
  },
  {
    id: "compiler-43",
    course: "compiler",
    lecture: "目标代码",
    topic: "寄存器分配",
    question: "寄存器冲突图中相邻的两个变量通常表示什么？",
    options: ["它们活跃期冲突，不能分配到同一寄存器", "它们一定是同一个变量", "它们必须在同一基本块开头定义", "它们都是 DFA 终态"],
    answer: 0,
    source: "Arthals《目标代码生成》https://arthals.ink/blog/code-generation",
    detail: "寄存器分配常建模为图着色：冲突图中有边的变量不能共用同一寄存器。"
  },
  {
    id: "compiler-44",
    course: "compiler",
    lecture: "目标代码",
    topic: "spill",
    question: "寄存器分配中的 spill 操作指什么？",
    options: ["寄存器不足时把某些值溢出保存到内存/栈中", "把 DFA 状态拆分", "把文法改成 LL(1)", "把所有代码删除"],
    answer: 0,
    source: "Arthals《目标代码生成》https://arthals.ink/blog/code-generation",
    detail: "当可用寄存器不足以容纳所有冲突变量时，需要将部分值 spill 到内存位置，再在需要时加载回来。"
  },
  {
    id: "compiler-45",
    course: "compiler",
    lecture: "优化",
    topic: "优化原则",
    question: "代码优化的首要原则是什么？",
    options: ["保证语义/可观察行为不变", "让代码越短越好而不管结果", "删除所有循环", "强制所有变量进同一寄存器"],
    answer: 0,
    source: "Arthals《程序优化》https://arthals.ink/blog/optimization",
    detail: "笔记明确写出代码优化原则：首先保证安全，即确保语义或可观察行为不变，然后提高效率。"
  },
  {
    id: "compiler-46",
    course: "compiler",
    lecture: "优化",
    topic: "优化阶段",
    question: "机器无关优化通常更适合在哪类代码上进行？",
    options: ["中间代码", "最终机器码二进制补丁", "源文件注释", "DFA 初态"],
    answer: 0,
    source: "Arthals《程序优化》https://arthals.ink/blog/optimization",
    detail: "笔记把中间代码生成阶段列为机器无关优化的位置，目标代码生成阶段则涉及机器有关优化。"
  },
  {
    id: "compiler-47",
    course: "compiler",
    lecture: "优化",
    topic: "数据流分析",
    question: "活跃变量分析属于哪类分析？",
    options: ["数据流分析", "词法最长匹配", "文法二义性消除", "垃圾回收标记算法"],
    answer: 0,
    source: "Arthals《程序优化》https://arthals.ink/blog/optimization",
    detail: "程序优化笔记列出数据流抽象、前向/后向分析模式以及活跃变量、到达定值、可用表达式等分析。"
  },
  {
    id: "compiler-48",
    course: "compiler",
    lecture: "优化",
    topic: "到达定值",
    question: "到达定值分析通常关心什么？",
    options: ["某变量定义是否可能沿某路径到达程序点且未被覆盖", "DFA 是否最小", "过程返回地址是否在栈顶", "对象引用计数是否为 0"],
    answer: 0,
    source: "Arthals《程序优化》https://arthals.ink/blog/optimization",
    detail: "到达定值是经典前向数据流分析，用于判断某个定义是否能到达某个程序点。"
  },
  {
    id: "compiler-49",
    course: "compiler",
    lecture: "优化",
    topic: "可用表达式",
    question: "可用表达式分析常用于支持哪类优化？",
    options: ["公共子表达式消除", "词法错误恢复", "LR(1) 展望符构造", "运行时栈帧创建"],
    answer: 0,
    source: "Arthals《程序优化》https://arthals.ink/blog/optimization",
    detail: "可用表达式分析判断表达式值是否已经计算且操作数未改变，常用于公共子表达式消除。"
  },
  {
    id: "compiler-50",
    course: "compiler",
    lecture: "测试点",
    topic: "短路求值",
    question: "编译原理测试点笔记提醒，逻辑表达式返回值应当是什么类型语义？",
    options: ["布尔类型语义", "任意数组指针", "活动记录指针", "DFA 状态编号"],
    answer: 0,
    source: "Arthals《编译原理大作业的奇妙测试点们》https://arthals.ink/blog/compile-principle-testcases",
    detail: "笔记在短路求值测试点中提醒，逻辑表达式返回值一定是布尔类型，不能简单被错误常量传播处理。"
  },
  {
    id: "os-1",
    course: "os",
    lecture: "OS 概念",
    topic: "操作系统作用",
    question: "课件把操作系统概括为 Referee、Illusionist 和 Glue，其中 Illusionist 主要强调什么？",
    options: ["提供干净、易用的硬件抽象，例如虚拟内存和文件", "只负责给所有程序平均分配 CPU", "只处理网络协议，不管理本机资源", "把应用程序直接暴露给裸硬件"],
    answer: 0,
    source: "lec02_concepts.pdf · 第 2-3 页",
    detail: "Illusionist 指操作系统通过抽象和虚拟化掩盖硬件复杂性，让程序看到更简单的资源模型；Referee 更强调保护、隔离和共享。"
  },
  {
    id: "os-2",
    course: "os",
    lecture: "OS 概念",
    topic: "四个基本概念",
    question: "课件列出的四个操作系统基本概念不包括哪一项？",
    options: ["线程", "地址空间", "进程", "编译优化"],
    answer: 3,
    source: "lec02_concepts.pdf · 第 11 页；lec03_abstraction1.pdf · 第 2 页",
    detail: "四个基本概念是线程、带转换的地址空间、进程、双模式操作/保护。编译优化属于编译器主题，不是这里的 OS 基本概念。"
  },
  {
    id: "os-3",
    course: "os",
    lecture: "OS 概念",
    topic: "进程",
    question: "按照课件定义，进程更接近下面哪种说法？",
    options: ["一个执行中程序的环境，包含地址空间和一个或多个控制线程", "CPU 中的一个加法器", "磁盘上的一个普通目录", "只包含一条机器指令的对象"],
    answer: 0,
    source: "lec02_concepts.pdf · 第 18 页；lec03_abstraction1.pdf · 第 2 页",
    detail: "进程封装执行环境和受限权限，拥有内存地址空间、线程、文件描述符、文件系统上下文等。"
  },
  {
    id: "os-4",
    course: "os",
    lecture: "线程与进程",
    topic: "线程状态",
    question: "线程处于 READY 状态时，最准确的含义是什么？",
    options: ["正在 CPU 上运行", "可以运行但当前没有占用 CPU", "永久结束且不能恢复", "正在等待 I/O，不能被调度"],
    answer: 1,
    source: "lec03_abstraction1.pdf · 第 12 页",
    detail: "课件把线程状态概括为 RUNNING、READY、BLOCKED。READY 表示具备运行条件，只是暂时没有被调度到处理器上。"
  },
  {
    id: "os-5",
    course: "os",
    lecture: "线程与进程",
    topic: "线程私有状态",
    question: "多线程进程中，通常属于每个线程私有状态的是哪一项？",
    options: ["全局变量", "堆区对象", "寄存器和栈", "打开文件描述符表"],
    answer: 2,
    source: "lec03_abstraction1.pdf · 第 22 页",
    detail: "课件区分了进程内线程共享的内存与 I/O 状态，以及线程私有的 TCB、寄存器、栈等执行上下文。"
  },
  {
    id: "os-6",
    course: "os",
    lecture: "线程与进程",
    topic: "并发目标",
    question: "课件中 MTAO（multiple things at once）主要说明为什么需要线程？",
    options: ["为了让磁盘容量变大", "为了同时处理进程、I/O、中断、多个连接等任务", "为了取消所有上下文切换", "为了让单线程程序不能访问内存"],
    answer: 1,
    source: "lec03_abstraction1.pdf · 第 6-7 页",
    detail: "操作系统和服务器常常需要同时处理多个活动，线程提供了 OS 级并发单位，使每个线程可以代表一件正在处理的事。"
  },
  {
    id: "os-7",
    course: "os",
    lecture: "线程与进程",
    topic: "Multiprocessing",
    question: "Multiprocessing 和 Multiprogramming 的区别，哪一项最符合课件表述？",
    options: ["二者完全相同", "Multiprocessing 指多个 CPU/核心，Multiprogramming 指多个任务共享同一 CPU", "Multiprogramming 只用于文件系统", "Multiprocessing 只表示多个文件描述符"],
    answer: 1,
    source: "lec03_abstraction1.pdf · 第 8 页",
    detail: "课件定义 Multiprocessing 为多个 CPU 或核心；Multiprogramming 指多个作业/进程通过时间复用共享处理器。"
  },
  {
    id: "os-8",
    course: "os",
    lecture: "线程与进程",
    topic: "Fork-Join",
    question: "Fork-Join 模式中 join 的主要作用是什么？",
    options: ["关闭所有文件描述符", "创建新地址空间但不运行", "等待子线程完成并收集结果", "把页表改成只读"],
    answer: 2,
    source: "lec03_abstraction1.pdf · 第 20 页",
    detail: "Fork-Join 中主线程 fork 出多个子线程并分配任务，随后通过 join 等待它们结束并汇总结果。"
  },
  {
    id: "os-9",
    course: "os",
    lecture: "线程与进程",
    topic: "竞态条件",
    question: "Race condition 的核心问题是什么？",
    options: ["程序运行结果依赖线程交错执行顺序", "所有线程一定严格串行执行", "进程不能打开文件", "CPU 无法产生中断"],
    answer: 0,
    source: "lec03_abstraction1.pdf · 第 44 页",
    detail: "竞态条件发生在并发执行访问共享状态时，不同调度顺序可能导致不同结果，通常需要同步来约束关键操作。"
  },
  {
    id: "os-10",
    course: "os",
    lecture: "线程与进程",
    topic: "互斥",
    question: "Mutual Exclusion 主要保证什么？",
    options: ["线程永远不会阻塞", "只允许一个线程在同一时刻执行某段关键操作", "每个进程都使用同一个地址空间", "所有 I/O 都立即完成"],
    answer: 1,
    source: "lec03_abstraction1.pdf · 第 47 页；lec07_synchronization2.pdf · 第 9 页",
    detail: "互斥用于保护临界区，让同一时间只有一个线程访问需要原子性的共享数据操作。"
  },
  {
    id: "os-11",
    course: "os",
    lecture: "文件与 I/O",
    topic: "Everything is a File",
    question: "Unix/POSIX 中 Everything is a File 的思想主要意味着什么？",
    options: ["只有磁盘普通文件可以读写", "文件、设备、socket、pipe 等尽量使用统一接口", "所有文件都必须存进寄存器", "网络通信不能通过系统调用完成"],
    answer: 1,
    source: "lec04_abstraction2.pdf · 第 3 页",
    detail: "课件说明 Unix/POSIX 用 open、read、write、close 等统一接口处理磁盘文件、设备、网络 socket 和本地 IPC。"
  },
  {
    id: "os-12",
    course: "os",
    lecture: "文件与 I/O",
    topic: "文件抽象",
    question: "POSIX 文件数据在课件中被抽象为什么？",
    options: ["一个固定长度的整数", "只能按记录访问的数据库表", "字节序列", "CPU 调度队列"],
    answer: 2,
    source: "lec04_abstraction2.pdf · 第 5 页",
    detail: "课件把文件定义为文件系统中有名字的数据集合，POSIX 文件数据模型是 sequence of bytes。"
  },
  {
    id: "os-13",
    course: "os",
    lecture: "文件与 I/O",
    topic: "高低层 I/O",
    question: "C 标准库的 FILE* 与底层文件描述符的关系，哪项正确？",
    options: ["FILE* 只存在于内核，用户态不可见", "FILE* 通常封装文件描述符、缓冲区和锁等信息", "文件描述符一定比 FILE* 更高级", "FILE* 不能进行任何缓冲"],
    answer: 1,
    source: "lec04_abstraction2.pdf · 第 27 页",
    detail: "课件说明 fopen 返回的 FILE* 包含底层 file descriptor、用户态缓冲区以及多线程使用时的锁。"
  },
  {
    id: "os-14",
    course: "os",
    lecture: "文件与 I/O",
    topic: "用户态缓冲",
    question: "为什么高层 I/O 库通常要在用户态做缓冲？",
    options: ["为了减少频繁系统调用带来的开销", "为了禁止顺序读写", "为了让每个字节都触发一次磁盘寻道", "为了绕过所有权限检查"],
    answer: 0,
    source: "lec04_abstraction2.pdf · 第 33 页",
    detail: "系统调用比普通函数调用更昂贵。用户态缓冲能把多次小读写合并，显著降低 syscall 次数。"
  },
  {
    id: "os-15",
    course: "os",
    lecture: "文件与 I/O",
    topic: "fork 与文件描述符",
    question: "进程 fork 后，父子进程的文件描述符通常会怎样？",
    options: ["子进程一定没有任何文件描述符", "父子进程的描述符会引用/别名到底层 open file description", "所有文件立刻被删除", "文件偏移量一定互不影响"],
    answer: 1,
    source: "lec04_abstraction2.pdf · 第 43 页",
    detail: "课件图示 fork 后文件描述符被复制，但底层 open file description 可能被父子进程共同引用，因此偏移等状态可能共享。"
  },
  {
    id: "os-16",
    course: "os",
    lecture: "IPC",
    topic: "Pipe",
    question: "关于 POSIX/Unix pipe，哪项说法最符合课件？",
    options: ["pipe 是无限大的共享内存", "pipe 中没有缓冲区", "pipe 可看作有限缓冲的进程间字节流通信", "pipe 只能跨互联网使用"],
    answer: 2,
    source: "lec06_synchronization1.pdf · 第 2 页；lec05_abstraction3.pdf · 第 1-3 页",
    detail: "pipe 连接写端和读端，中间是有限缓冲区；写满可能阻塞，读空也可能阻塞，接口仍类似文件 I/O。"
  },
  {
    id: "os-17",
    course: "os",
    lecture: "IPC",
    topic: "Socket",
    question: "Socket 抽象的关键思想是什么？",
    options: ["把跨机器通信也尽量做成类似文件 I/O 的端点读写", "只用于本地内存分配", "只能表示磁盘扇区", "只在编译期存在"],
    answer: 0,
    source: "lec06_synchronization1.pdf · 第 3-6 页",
    detail: "socket 是通信端点，课件强调跨世界的通信看起来像 File I/O，读写 socket 类似读写文件描述符。"
  },
  {
    id: "os-18",
    course: "os",
    lecture: "IPC",
    topic: "TCP 连接建立",
    question: "服务器端 socket 中 accept 的结果通常是什么？",
    options: ["关闭监听 socket", "返回一个用于该客户端连接的新 socket", "把 IP 地址改成 0", "立即删除所有客户端状态"],
    answer: 1,
    source: "lec05_abstraction3.pdf · 第 37 页",
    detail: "课件区分 server socket 和 connection socket：监听 socket 接收连接请求，accept 后得到与某个客户端通信的新 socket。"
  },
  {
    id: "os-19",
    course: "os",
    lecture: "同步",
    topic: "PCB",
    question: "PCB（Process Control Block）通常不包含哪类信息？",
    options: ["运行/就绪/阻塞等状态", "进程 ID 和用户信息", "未运行时保存的寄存器状态", "整门课程所有 PPT 的原始文件"],
    answer: 3,
    source: "lec06_synchronization1.pdf · 第 10 页",
    detail: "PCB 是内核表示进程的数据结构，包含状态、寄存器、PID、用户、执行时间、地址空间等管理信息。"
  },
  {
    id: "os-20",
    course: "os",
    lecture: "同步",
    topic: "上下文切换",
    question: "上下文切换中，操作系统最核心的动作是什么？",
    options: ["只改变显示器亮度", "保存当前线程 CPU 状态并装入下一个线程状态", "把所有磁盘块清零", "重新编译应用程序"],
    answer: 1,
    source: "lec06_synchronization1.pdf · 第 11 页；第 57 页",
    detail: "课件总结并发通过 CPU 时间复用实现：卸载当前线程的 PC/寄存器等状态，加载新线程状态。"
  },
  {
    id: "os-21",
    course: "os",
    lecture: "同步",
    topic: "原子操作",
    question: "Atomic Operation 的含义最接近哪一项？",
    options: ["一定非常慢的操作", "永远只能在用户态执行的操作", "运行时不可被观察到中间状态、要么完成要么不发生的操作", "只读磁盘不读内存的操作"],
    answer: 2,
    source: "lec07_synchronization2.pdf · 第 8 页",
    detail: "理解并发程序需要知道底层哪些操作不可分割。原子操作总是完整运行，不能被其他线程看到半完成状态。"
  },
  {
    id: "os-22",
    course: "os",
    lecture: "同步",
    topic: "锁",
    question: "给银行账户更新代码加锁的主要目的是什么？",
    options: ["增加临界区中的并发写入数量", "保护关键区，防止共享账户状态被并发破坏", "让所有线程都永久睡眠", "取消所有 CPU 调度"],
    answer: 1,
    source: "lec07_synchronization2.pdf · 第 9 页",
    detail: "课件用银行服务例子说明：找到临界区后 acquire lock，保证同一时刻只有一个线程修改共享账户数据。"
  },
  {
    id: "os-23",
    course: "os",
    lecture: "同步",
    topic: "关中断实现锁",
    question: "单纯用关闭中断实现锁的主要局限是什么？",
    options: ["在多处理器上不能阻止其他 CPU 的线程同时执行临界区", "会自动解决所有死锁", "只能用于文件名解析", "会让磁盘寻道变为 0"],
    answer: 0,
    source: "lec08_synchronization3.pdf · 第 14 页；lec09_synchronization4.pdf · 第 2 页",
    detail: "关闭本 CPU 中断可以避免本地被抢占，但多核环境下其他 CPU 仍可能运行并访问共享数据，因此需要硬件原子指令等机制。"
  },
  {
    id: "os-24",
    course: "os",
    lecture: "同步",
    topic: "硬件原子指令",
    question: "Test-and-Set、Compare-and-Swap 这类指令常用于做什么？",
    options: ["压缩图片", "实现锁等同步原语的底层原子步骤", "改变网页颜色", "计算磁盘柱面数"],
    answer: 1,
    source: "lec07_synchronization2.pdf · 第 19 页；lec08_synchronization3.pdf · 第 5 页",
    detail: "课件的同步层次图把 Test&Set、Compare&Swap 放在硬件 Load/Store 之上，用于构造锁、信号量、监视器等同步抽象。"
  },
  {
    id: "os-25",
    course: "os",
    lecture: "同步",
    topic: "信号量",
    question: "信号量（Semaphore）在课件中的基本定义是什么？",
    options: ["一个非负整数值，配合 P/V 或 down/up 操作用于同步", "只保存文件扩展名的字符串", "CPU 的物理序列号", "只能由编译器使用的语法树节点"],
    answer: 0,
    source: "lec03_abstraction1.pdf · 第 52 页；lec07_synchronization2.pdf · 第 14 页",
    detail: "信号量是 Dijkstra 提出的广义锁，内部有非负整数值，可用于互斥或资源计数。"
  },
  {
    id: "os-26",
    course: "os",
    lecture: "同步",
    topic: "生产者消费者",
    question: "有界缓冲区的经典信号量解法中，emptySlots 通常表示什么？",
    options: ["已经装满的槽数", "缓冲区中空槽数量", "当前 CPU 核心数", "打开文件数量"],
    answer: 1,
    source: "lec08_synchronization3.pdf · 第 2-4 页",
    detail: "课件的 coke machine 例子中 fullSlots 初始为 0，emptySlots 初始为缓冲区大小，mutex 保护缓冲区本身。"
  },
  {
    id: "os-27",
    course: "os",
    lecture: "同步",
    topic: "条件变量",
    question: "条件变量相比单独使用信号量，主要帮助表达什么？",
    options: ["等待某个受锁保护的条件成立，并在 signal/broadcast 后重新检查", "把磁盘块改成页表项", "直接替代所有进程地址空间", "让所有等待线程立即同时进入临界区"],
    answer: 0,
    source: "lec08_synchronization3.pdf · 第 40-44 页；lec09_synchronization4.pdf · 第 4 页",
    detail: "条件变量常与锁配合，线程在条件不满足时 wait，醒来后继续在锁保护下检查条件。Mesa 语义下通常要用 while 重新判断。"
  },
  {
    id: "os-28",
    course: "os",
    lecture: "同步",
    topic: "Monitor",
    question: "Monitor（监视器）通常把哪些东西组合起来？",
    options: ["磁盘扇区和网络包", "共享数据、互斥锁和条件变量等同步规则", "HTML 与 CSS", "虚拟地址和机器码注释"],
    answer: 1,
    source: "lec08_synchronization3.pdf · 第 40 页；lec09_synchronization4.pdf · 第 5-6 页",
    detail: "课件把监视器作为更高层同步抽象，封装共享状态、进入互斥以及条件等待/通知逻辑。"
  },
  {
    id: "os-29",
    course: "os",
    lecture: "同步",
    topic: "Mesa 与 Hoare",
    question: "Mesa monitor 与 Hoare monitor 的一个关键区别是什么？",
    options: ["Mesa 中 signaler 继续持有锁和处理器，waiter 进入就绪队列", "Mesa 禁止使用条件变量", "Hoare 中 signal 后 waiter 永远不会运行", "二者没有任何语义差别"],
    answer: 0,
    source: "lec09_synchronization4.pdf · 第 5-6 页；lec08_synchronization3.pdf · 第 44 页",
    detail: "Hoare 语义中 signal 后 waiter 立即运行；Mesa 语义中 signaler 继续执行，waiter 只是进入 ready queue，所以醒来要重新检查条件。"
  },
  {
    id: "os-30",
    course: "os",
    lecture: "同步",
    topic: "读者写者",
    question: "读者/写者问题的正确性约束中，哪项是正确的？",
    options: ["多个写者可以同时写同一数据库", "读者只有在没有写者时才能读，写者需要独占访问", "读者和写者永远不能等待", "读者必须逐个串行读，不能并发"],
    answer: 1,
    source: "lec09_synchronization4.pdf · 第 10 页",
    detail: "课件要求：无写者时多个读者可并发读；写者访问时不能有读者或其他写者；同一时间最多一个写者。"
  },
  {
    id: "os-31",
    course: "os",
    lecture: "调度",
    topic: "FCFS",
    question: "FCFS 调度策略的基本规则是什么？",
    options: ["每次随机选择一个线程", "谁先到达就先运行，类似 FIFO", "总是选择截止时间最早的任务", "总是选择票数最少的任务"],
    answer: 1,
    source: "lec10_scheduling1.pdf · 第 12 页",
    detail: "FCFS 即 First-Come, First-Served，也称 FIFO 或 run until done。它简单公平，但可能让短作业被长作业拖累。"
  },
  {
    id: "os-32",
    course: "os",
    lecture: "调度",
    topic: "Round Robin",
    question: "Round Robin 相比 FCFS 的关键变化是什么？",
    options: ["使用时间片，时间片到期后抢占并放回队尾", "永远不发生抢占", "只调度 I/O 设备不调度 CPU", "必须预知所有作业长度"],
    answer: 0,
    source: "lec10_scheduling1.pdf · 第 14 页；第 21 页",
    detail: "RR 使用 FIFO 队列，但每个作业最多运行一个 quantum；时间片到期由 timer interrupt 触发抢占。"
  },
  {
    id: "os-33",
    course: "os",
    lecture: "调度",
    topic: "SJF",
    question: "如果能预知未来，Shortest Job First 主要追求什么效果？",
    options: ["优先运行计算量最少的作业，以降低平均等待时间", "优先运行文件最大的作业", "让所有作业按 PID 倒序运行", "只运行内核线程"],
    answer: 0,
    source: "lec10_scheduling1.pdf · 第 28 页",
    detail: "SJF/SRTF 的思想是优先处理短作业，在理想预测下能改善平均等待时间，但现实中需要估计下一次 CPU burst。"
  },
  {
    id: "os-34",
    course: "os",
    lecture: "调度",
    topic: "优先级",
    question: "严格优先级调度的典型风险是什么？",
    options: ["低优先级任务可能长期得不到运行而饥饿", "所有任务一定完全公平", "无法表达任务重要性", "不能处理就绪队列"],
    answer: 0,
    source: "lec11_scheduling2.pdf · 第 4 页；第 36 页",
    detail: "优先级调度能表达重要性，但如果高优先级任务持续到来，低优先级或长任务可能长期等待。"
  },
  {
    id: "os-35",
    course: "os",
    lecture: "调度",
    topic: "Lottery Scheduling",
    question: "Lottery Scheduling 如何体现比例份额？",
    options: ["每次固定运行最短作业", "给作业分配彩票，按抽中概率获得 CPU 时间片", "只运行没有文件描述符的进程", "让所有任务同时占用同一 CPU"],
    answer: 1,
    source: "lec11_scheduling2.pdf · 第 7-8 页",
    detail: "彩票调度给每个作业若干 tickets，每个时间片随机抽取中奖彩票；长期平均 CPU 份额与彩票数量成比例。"
  },
  {
    id: "os-36",
    course: "os",
    lecture: "调度",
    topic: "实时调度",
    question: "实时调度最强调哪一类目标？",
    options: ["页面颜色一致", "预测最坏响应时间并满足 deadline", "让吞吐量永远等于 0", "只优化磁盘空间"],
    answer: 1,
    source: "lec11_scheduling2.pdf · 第 17 页；lec12_scheduling3.pdf · 第 2-3 页",
    detail: "实时系统关心性能的可预测性，需要有信心地给出最坏响应时间，保证任务在截止时间前完成。"
  },
  {
    id: "os-37",
    course: "os",
    lecture: "调度",
    topic: "EDF",
    question: "Earliest Deadline First（EDF）的调度依据是什么？",
    options: ["截止时间越早，优先级越高", "PID 越大，优先级越高", "文件越小，优先级越高", "栈越深，优先级越高"],
    answer: 0,
    source: "lec12_scheduling3.pdf · 第 3 页",
    detail: "EDF 是动态优先级策略，周期任务或实时任务中，距离 deadline 最近的任务优先运行。"
  },
  {
    id: "os-38",
    course: "os",
    lecture: "调度",
    topic: "优先级反转",
    question: "优先级捐赠/继承主要用于缓解什么问题？",
    options: ["缓解高优先级任务被持锁的低优先级任务间接阻塞的优先级反转", "消除所有页表", "减少文件名长度", "替代所有中断处理"],
    answer: 0,
    source: "lec11_scheduling2.pdf · 第 32-34 页；lec12_scheduling3.pdf · 第 5-6 页",
    detail: "当高优先级任务等待低优先级持有的锁，而中优先级任务抢占低优先级任务时会出现优先级反转；捐赠让低优先级临时继承较高优先级。"
  },
  {
    id: "os-39",
    course: "os",
    lecture: "调度",
    topic: "MLFQ",
    question: "MLFQ 中长时间占用 CPU 的计算型任务通常会怎样？",
    options: ["被提升到最高优先级且永不下降", "可能被逐步降到较低优先级队列", "立即删除进程地址空间", "被转成磁盘块"],
    answer: 1,
    source: "lec11_scheduling2.pdf · 第 36 页",
    detail: "课件讨论 SRTF 和 MLFQ 的饥饿问题时指出，长时间运行的计算任务可能被降级到低优先级。"
  },
  {
    id: "os-40",
    course: "os",
    lecture: "死锁",
    topic: "死锁与饥饿",
    question: "课件如何区分 starvation 和 deadlock？",
    options: ["二者完全相同", "死锁是一种特殊且致命的饥饿，线程彼此等待导致都无法继续", "饥饿一定表示所有线程互相持锁", "死锁只会发生在编译器中"],
    answer: 1,
    source: "lec12_scheduling3.pdf · 第 4 页；第 12 页",
    detail: "Starvation 是线程长期无法取得进展；deadlock 中一组线程因循环等待资源而都无法继续，属于更强的失败模式。"
  },
  {
    id: "os-41",
    course: "os",
    lecture: "死锁",
    topic: "必要条件",
    question: "下面哪项不是课件总结的死锁四个必要条件之一？",
    options: ["互斥", "持有并等待", "不可抢占", "页面一定命中 TLB"],
    answer: 3,
    source: "lec12_scheduling3.pdf · 第 45 页",
    detail: "死锁四条件是 mutual exclusion、hold and wait、no preemption、circular wait。TLB 命中与死锁条件无关。"
  },
  {
    id: "os-42",
    course: "os",
    lecture: "死锁",
    topic: "Banker 算法",
    question: "Banker 算法避免死锁的关键思想是什么？",
    options: ["要求提前声明最大资源需求，只允许系统进入安全状态", "随机杀掉所有线程", "把所有资源永久锁住", "禁止任何进程请求资源"],
    answer: 0,
    source: "lec12_scheduling3.pdf · 第 39 页",
    detail: "Banker 算法根据可用资源、已分配资源和最大需求判断是否存在安全执行序列，只有安全时才批准请求。"
  },
  {
    id: "os-43",
    course: "os",
    lecture: "内存",
    topic: "Base and Bound",
    question: "Base and Bound 机制的主要用途是什么？",
    options: ["给每个进程限定可访问物理地址范围，实现简单保护和重定位", "为网络包计算校验和", "实现彩票调度", "存储文件目录项"],
    answer: 0,
    source: "lec14_memory1.pdf · 第 10 页；lec03_abstraction1.pdf · 第 3-4 页",
    detail: "Base and Bound 用 base 和 bound 检查/转换程序地址，能隔离程序和保护 OS，但灵活性有限。"
  },
  {
    id: "os-44",
    course: "os",
    lecture: "内存",
    topic: "分段",
    question: "分段机制更自然地对应程序员看到的哪些逻辑区域？",
    options: ["代码段、数据段、栈等不同逻辑段", "磁盘柱面和扇区", "彩票和时间片", "TCP 端口号"],
    answer: 0,
    source: "lec14_memory1.pdf · 第 15-16 页",
    detail: "更灵活的 segmentation 允许按逻辑视图划分多个段，如 code、data、stack，也可用于共享，但会带来外部碎片等问题。"
  },
  {
    id: "os-45",
    course: "os",
    lecture: "内存",
    topic: "分页",
    question: "分页相对分段的一个重要优点是什么？",
    options: ["把物理内存切成固定大小页框，使每个页框等价，减少外部碎片问题", "完全不需要地址转换", "让每个进程只能有一个页面", "禁止虚拟内存"],
    answer: 0,
    source: "lec14_memory1.pdf · 第 26 页",
    detail: "分页把物理内存划成固定大小 chunk/page frame，任意虚拟页可映射到任意物理页框，更容易分配和回收。"
  },
  {
    id: "os-46",
    course: "os",
    lecture: "内存",
    topic: "页表",
    question: "页表的核心作用是什么？",
    options: ["把虚拟页号映射到物理页号，并保存有效位/权限等信息", "记录 Git 提交历史", "调度网络连接", "把所有文件压缩成一个字节"],
    answer: 0,
    source: "lec15_memory2.pdf · 第 4 页；第 8 页",
    detail: "页表是从 VPN 到 PPN 的映射函数，PTE 中还会包含 valid、read/write 等保护和状态位。"
  },
  {
    id: "os-47",
    course: "os",
    lecture: "内存",
    topic: "上下文切换与页表",
    question: "使用分页时，进程上下文切换通常需要切换什么来实现不同地址空间？",
    options: ["页表指针和相关限制/上下文", "显示器分辨率", "文件扩展名", "鼠标位置"],
    answer: 0,
    source: "lec15_memory2.pdf · 第 7 页",
    detail: "不同进程的虚拟地址通过不同页表翻译。上下文切换时需要切换页表指针等状态，并依赖 dual-mode 防止用户程序修改页表。"
  },
  {
    id: "os-48",
    course: "os",
    lecture: "内存",
    topic: "TLB",
    question: "TLB 在地址转换中的角色是什么？",
    options: ["缓存最近使用的虚拟页到物理页转换结果", "保存所有磁盘目录名", "作为 CPU 调度队列", "替代所有物理内存"],
    answer: 0,
    source: "lec15_memory2.pdf · 第 1 页；lec16_memory3.pdf · 第 9-11 页",
    detail: "TLB 是地址转换缓存，用于避免每次访存都走完整页表；它位于内存访问关键路径上，必须非常快。"
  },
  {
    id: "os-49",
    course: "os",
    lecture: "内存",
    topic: "多级页表",
    question: "多级页表主要想解决什么问题？",
    options: ["减少稀疏虚拟地址空间下页表占用的内存", "让所有页面都必须连续存放", "让页大小变成 1 bit", "取消虚拟地址"],
    answer: 0,
    source: "lec16_memory3.pdf · 第 5-6 页；lec15_memory2.pdf · 第 7-8 页",
    detail: "多级页表把页表组织成树，只为实际使用的虚拟地址范围分配下级页表，适合稀疏地址空间。"
  },
  {
    id: "os-50",
    course: "os",
    lecture: "内存",
    topic: "Page Fault",
    question: "Page Fault 发生的典型原因是什么？",
    options: ["虚拟到物理地址转换失败，例如 PTE 无效或权限违规", "浏览器刷新页面", "进程创建了太多文件名", "CPU 时间片正常到期"],
    answer: 0,
    source: "lec16_memory3.pdf · 第 19 页",
    detail: "课件说明 page fault 是同步 fault/trap，可能由 PTE invalid、权限级别不符、访问违规或映射不存在引起。"
  },
  {
    id: "os-51",
    course: "os",
    lecture: "内存",
    topic: "Demand Paging",
    question: "Demand Paging 的基本思想是什么？",
    options: ["只把活跃页留在内存，访问不在内存的页时再通过 page fault 调入", "启动时把整个磁盘读入寄存器", "禁止进程使用堆", "让所有页永不换出"],
    answer: 0,
    source: "lec15_memory2.pdf · 第 11 页；lec16_memory3.pdf · 第 1 页",
    detail: "Demand Paging 把 DRAM 当作磁盘上虚拟页的缓存，页表记录哪些页在内存，缺页时由 OS 载入。"
  },
  {
    id: "os-52",
    course: "os",
    lecture: "内存",
    topic: "Copy on Write",
    question: "UNIX fork 中 Copy-on-Write 的核心做法是什么？",
    options: ["父子进程先共享只读页面，真正写入时再复制页面", "fork 时立即复制整个磁盘", "让父子进程永远共享可写页面", "删除父进程的地址空间"],
    answer: 0,
    source: "lec15_memory2.pdf · 第 11 页；lec16_memory3.pdf · 第 29 页",
    detail: "Copy-on-Write 让 fork 初期父子页表指向同一物理页并标记不可写，写入触发 fault 后才复制。"
  },
  {
    id: "os-53",
    course: "os",
    lecture: "内存",
    topic: "Working Set",
    question: "Working Set 模型描述的是什么？",
    options: ["程序执行过程中一段时间内活跃使用的地址集合", "所有文件系统目录名集合", "所有 CPU 支持的指令集合", "所有网络端口集合"],
    answer: 0,
    source: "lec16_memory3.pdf · 第 44 页",
    detail: "课件指出程序执行会在不同 working sets 之间转换；如果内存无法容纳活跃集合，缺页会显著增多。"
  },
  {
    id: "os-54",
    course: "os",
    lecture: "内存",
    topic: "页替换",
    question: "为什么页面替换策略特别重要？",
    options: ["选错页面会导致访问磁盘，代价很高", "它决定所有进程的用户名", "它可以消除所有程序 bug", "它会直接改变网页标题"],
    answer: 0,
    source: "lec17_memory4.pdf · 第 5-7 页",
    detail: "页面替换是缓存替换的一种，但页面 miss 往往要访问磁盘，错误替换的成本远高于普通 CPU cache miss。"
  },
  {
    id: "os-55",
    course: "os",
    lecture: "内存",
    topic: "Clock 算法",
    question: "Clock 页面替换算法近似的是哪种策略？",
    options: ["LRU", "FCFS CPU 调度", "两阶段提交", "文件路径解析"],
    answer: 0,
    source: "lec17_memory4.pdf · 第 18 页；第 35 页",
    detail: "Clock 使用 use/reference bit 和时钟指针寻找最近未使用的页面，是 LRU 的低开销近似。"
  },
  {
    id: "os-56",
    course: "os",
    lecture: "I/O",
    topic: "总线",
    question: "Bus（总线）在 I/O 系统中的作用是什么？",
    options: ["一组连接硬件设备的公共线和协议，用于传输事务", "只保存用户密码", "只负责 CPU 算术运算", "操作系统中的线程状态"],
    answer: 0,
    source: "lec19_IO.pdf · 第 7-8 页",
    detail: "总线让多个设备通过一组公共连接和协议通信，避免每两个设备之间都建立独立连接。"
  },
  {
    id: "os-57",
    course: "os",
    lecture: "I/O",
    topic: "DMA",
    question: "DMA 在 I/O 传输中的主要好处是什么？",
    options: ["设备可直接与内存传输数据，减少 CPU 逐字节搬运负担", "让磁盘变成寄存器", "取消所有中断", "把文件系统改成 FAT"],
    answer: 0,
    source: "lec19_IO.pdf · 第 5 页",
    detail: "课件图中 I/O 控制器可通过 DMA transfer 与主存交换数据，CPU 不必亲自搬运每个字节。"
  },
  {
    id: "os-58",
    course: "os",
    lecture: "I/O",
    topic: "设备驱动",
    question: "Device Driver 的定位是什么？",
    options: ["内核中与特定设备硬件直接交互的代码，同时向上提供标准接口", "浏览器插件", "普通用户的文本文件", "只用于编译源代码的程序"],
    answer: 0,
    source: "lec19_IO.pdf · 第 22 页",
    detail: "设备驱动是内核中的设备相关代码，负责和硬件交互，同时让上层 OS I/O 子系统看到统一接口。"
  },
  {
    id: "os-59",
    course: "os",
    lecture: "文件系统",
    topic: "磁盘访问",
    question: "磁盘读写数据通常可分为哪几个阶段？",
    options: ["寻道、旋转等待、数据传输", "词法分析、语法分析、代码生成", "fork、exec、join", "commit、push、merge"],
    answer: 0,
    source: "lec20_file1.pdf · 第 6 页",
    detail: "课件介绍磁盘结构时指出读写包括 seek time、rotational latency 和 transfer time 等阶段。"
  },
  {
    id: "os-60",
    course: "os",
    lecture: "文件系统",
    topic: "排队论",
    question: "I/O 排队系统中，当请求到达率接近服务率时，通常会发生什么？",
    options: ["队列等待时间急剧上升", "等待时间必然为 0", "磁盘容量自动翻倍", "CPU 不再需要调度"],
    answer: 0,
    source: "lec20_file1.pdf · 第 18-20 页",
    detail: "课件的小排队论部分强调系统接近平衡极限时，利用率升高会显著放大等待时间。"
  },
  {
    id: "os-61",
    course: "os",
    lecture: "文件系统",
    topic: "FAT",
    question: "FAT 文件系统中 File Allocation Table 的核心作用是什么？",
    options: ["记录文件块链/下一块位置，帮助把文件号和块序列映射到磁盘块", "保存 CPU 寄存器", "实现条件变量 wait", "调度实时任务"],
    answer: 0,
    source: "lec21_file2.pdf · 第 8-9 页；lec22_file3.pdf · 第 2 页",
    detail: "FAT 通过表项组织文件的块链，是早期 MS-DOS 文件系统的核心数据结构，至今仍有使用。"
  },
  {
    id: "os-62",
    course: "os",
    lecture: "文件系统",
    topic: "inode",
    question: "Unix inode 通常保存什么？",
    options: ["文件元数据和指向数据块的索引信息", "线程当前的 PC 寄存器", "网页的 CSS 样式", "彩票调度的随机种子"],
    answer: 0,
    source: "lec20_file1.pdf · 第 39 页；lec21_file2.pdf · 第 16 页",
    detail: "inode 对应一个文件，保存权限、大小等元数据和定位数据块的索引；文件号 inumber 可看作 inode 数组下标。"
  },
  {
    id: "os-63",
    course: "os",
    lecture: "文件系统",
    topic: "mmap",
    question: "Memory Mapped File 的核心效果是什么？",
    options: ["把文件内容映射进进程虚拟地址空间，通过内存访问触发读写", "把所有文件名映射成端口号", "强制文件只能顺序读取", "让文件系统不再需要缓存"],
    answer: 0,
    source: "lec22_file3.pdf · 第 7-10 页",
    detail: "mmap 让文件页进入进程地址空间，访问时可由 page fault handler 建立页表项并从文件读入数据。"
  },
  {
    id: "os-64",
    course: "os",
    lecture: "文件系统",
    topic: "Journaling",
    question: "Journaling 文件系统提高可靠性的基本方法是什么？",
    options: ["先把更新作为事务记录到日志/意图列表，再安全地修改磁盘结构", "直接跳过所有磁盘写入", "每次写入都随机选择块", "禁止目录项存在"],
    answer: 0,
    source: "lec23_file4.pdf · 第 16 页",
    detail: "课件说明 journaling 不直接修改磁盘数据结构，而是先把每个更新作为 transaction 写到 journal/intention list 中，便于崩溃恢复。"
  }
];
